<p>Summer is here!</p>

<p>What does that mean to you? Probably time for video games, hanging out with friends, enjoying the weather...</p>

<p>You&rsquo;re probably not thinking of cooping up in a hot room studying for the entire two months of &ldquo;freedom&rdquo;. That should be illegal during the summer, shouldn&rsquo;t it?</p>

<p>Well, I&rsquo;m challenging myself to do the illegal. The illegal to common sense.</p>

<p>I&rsquo;ve got a plan that will change my summer from a time of relaxation to anything but a time to relax.</p>

<p>This article will detail part one of the plan (the July half). A future article will detail part two of my plan (the August half).</p>

<h1>Shifting Summer School</h1>
<p>The news of &ldquo;summer school&rdquo; hit me just as I had everything planned out for my summer. I describe this event using &lsquo;hit&rsquo; because I was never aware that choosing one course over another would force me to take this course in summer school (or swap it out with a more useful course for next year, which I&rsquo;d rather not do). Perhaps this was completely my fault, but regardless, I&rsquo;m still pretty mad that this interruption ruined the plans that I had for using my summer well. In retaliation, I plan to make summer school useful, even if it becomes inconvenient for me.</p>

<h2>Plans</h2>
<p>Of course, summer schools exist to teach a particular subject I missed in my default courses. I was pretty disappointed in the disposal of half my summer until I realized that I had the option of taking these courses online. This allowed me to create a plan that shifted the center of summer school&rsquo;s focus to something that would provide value in the long run.</p>
<p>My first step was brainstorming ideas for altering summer school in my favour. I funneled the options down to a set of skills I wished to develop. You may find these goals familiar; my Impossible List categorizes them under  &ldquo;Efficiency Goals&rdquo;. I&rsquo;m enlisting the help of summer school to help me tackle three: Gregg Shorthand, Left-Hand Typing and Esperanto.</p>
<p>I originally planned to study computer algorithms over the summer. However, I believe that it&rsquo;s near impossible to incorporate computer algorithms as an aid to my summer school&rsquo;s progress. So, I took to searching for goals/skills I wanted to develop that I could incorporate into the courses. These three goals were perfect because I could use them in progressing with the actual material/assignments of the course.</p>
<p>I&rsquo;m incorporating these three goals into summer school in a pretty radical way. Normally, you would type your assignment and then submit it. Straightforwardness will not pertain to my process. My plan will involve writing my assignment with Gregg Shorthand and then typing it in Esperanto with my left hand. Of course, I wouldn&rsquo;t expect my teacher to understand Esperanto (at no fault of their own). I will be Google Translating my answer into English and fixing mistakes before I submit it (with my left hand). This process will be inefficient in the task at hand but will help me become fluent in more efficient skills.</p>
<p>The effort-to-value payoff can compare with the effort to reward ratio. Plain summer school on its own provides zero rewards. Sorry, it provides <em>negative</em> reward (eats up my time). This means that I need to balance this negative ratio by giving more rewards. It will not be enough to simply lessen the effort because the reward will still stay non-positive. I need to make reward positive to avoid a month of summer thrown in the trash. The amount of effort this extra reward requires will not matter as long as I make the reward become positive. Although, it is worth noting that there exists a line where too much effort for too much positivity may be too extreme. Now that I think about it, I may have crossed this line...</p>

<h3>Measuring Progress</h3>
<p>I want to observe the effects of nuclearizing my usage of these skills. As such, I plan to compare the fluency of these 3 skills at the start and at the end of this challenge. I plan to create a summary video that compares my skills at the start until the end, as Scott Young did after his Year Without English Challenge. I plan to measure my skill progress every Sunday with tests (e.g. writing test, typing test, translation test, etc.).</p>


<h3>Specifics</h3>
<h4>Gregg Shorthand</h4>
<p>There are many versions of Gregg Shorthand that one can learn. The version I will be using is the Anniversary Edition. I learned Gregg Shorthand from the Anniversary manual shared by <a href=&rdquo;http://gregg.angelfishy.net/&rdquo;>Andrew Owen on his Gregg Shorthand website.</a> It is worth pointing out that I will not be starting my goal from scratch: I have printed out the manual a year ago and as of writing this article, I am nearly three-fourths done with the manual. I have yet to use Gregg Shorthand in any large writing assignments or practical uses (due to my slow 20 WPM).</p>
<h4>Left-Hand Typing</h4>
<p>Left-Hand Typing isn&rsquo;t very popular, but I have found myself in cases where knowing how to type with one hand would have been extremely useful (especially when you want to use your mouse with your right hand for frequent navigation and use your left hand to type for frequent minor edits). The keyboard layout I will be typing on is a <a href=&rdquo;http://www.dvorak-keyboards.com/right_and_left_hand_dvorak_keyboard_layouts.htm&rdquo;>left hand Dvorak layout</a>, meaning the letters on the layout were specifically designed to make left-hand typing as efficient as possible. Currently, my typing speeds with my left-hand range from 30 to 40 WPM (when numbers and symbols are not included).</p>
<h4>Esperanto</h4>
<p>This skill may be the most in its infancy out of the three. I rarely practice Esperanto on Duolingo (I failed my bet with my friend!) and rarely ever use it. However, I still would love to be able to communicate in the most simple and straight-forward language there is and express my ideas with more simplicity and clarity using the universal language. I&rsquo;m currently learning Esperanto with the help of <a href=&rdquo;https://www.duolingo.com/&rdquo;>Duolingo</a>, <a href=&rdquo;https://www.clozemaster.com/&rdquo;>Clozemaster</a> and <a href=&rdquo;https://apps.ankiweb.net/&rdquo;>Anki</a> (for vocabulary). Creating a completely immersed experience with Esperanto may prove difficult because my summer school teachers don&rsquo;t speak Esperanto. At least, I don&rsquo;t believe they do, maybe I should ask...</p>

<h2>Accountability</h2>
<p>Accountability is a major issue with this challenge. I&rsquo;ve often found that when I make decisions that sacrifice efficiency, I often don&rsquo;t stick to them. The greatest fear for this project is not failing the course but rather my challenge. If I fail the course, I can retake it next year but if I fail the challenge, I waste a whole month of summer that could have been used in a much more effective manner. To keep myself accountable, I plan to use pre-commitment (this article is an example) and live accountability (by live streaming my progress).</p>
<h3>Pre-Commitment</h3>
<p>This article is a contributor to the strategy of pre-commitment. By publicly stating that I will be pursuing this extreme challenge, I&rsquo;ve put my words on the line and will have more motive in striving to keep my standards on par with the expectations I&rsquo;ve given myself.</p>
<p>There are many forms of pre-commitment. I&rsquo;ve recently read Nick Winter&rsquo;s list on his pre-commitments for skydiving. Some of these commitments include giving away a large sum of money for failure, having told a ton of people, already paying for it, and having already set the date in stone. I&rsquo;m still debating whether or not give away money for each time I fail...I might have to see how difficult the challenge is (I may be grossly underestimating it). So far, the only place I&rsquo;ve publicized this challenge is on this website...which is part of the Internet available to millions of people. The potential of others to see my progress is a strong enough commitment for my purposes. This will include the live streams as well. The date has already been set in stone. I have also made plans to keep interruptions kept to an absolute minimum.</p>

<h2>Motivators</h2>
<p>This challenge will be tough, especially on my sanity. However, now that I&rsquo;ve got my hands on a copy of Nick Winter&rsquo;s &ldquo;The Motivation Hacker&rdquo;, I think I may be a lot more prepared. In this section, I would like to build on the Motivation Equation and list some ways I plan to keep my motivation, many inspired by Nick Winter.</p>
<h3>Expectancy - Confidence of Success</h3>
<p>The most similar type of challenge I&rsquo;ve attempted are my SSSs, in which my most recent attempt was a success. I&rsquo;m a bit hesitant because based on previous experience, trying to do something repetitively and inefficiently can lead to frustration and a strong temptation to give up. I&rsquo;ve always come up with excuses and weasels, so I don&rsquo;t feel too strongly about my chances of success with such an extreme demand.</p>
<p>This is why it&rsquo;s important for me to focus on increasing the other positive factor (value) and decreasing the two negative factors (impulsiveness and delay) in this equation.</p>

<h3>Value - The Reward of the Finished Task</h3>
<p>This challenge may present another deficiency of a core motivating factor...it&rsquo;s hard to picture the final reward of this challenge. It&rsquo;s hard to really picture the improvement I&rsquo;m going to get out of this challenge because I have practiced these three skills but haven&rsquo;t really become fluent in any.</p>
<p>On the other hand, a skill that I have developed fluently through a nuclear restriction (only allowing myself to use this skill when I need it) is the Dvorak Keyboard Layout. When I challenged myself to learn this layout, I stuck to it and didn&rsquo;t weasel out even if my typing was as slow as a first grader&rsquo;s. Naturally, I improved really quickly and was able to climb back to my normal QWERTY speed in around 4 months or so. In fact, I was able to reach a record of 152 WPM (and finally finish a goal on my Impossible List), which was much faster than anything I could&rsquo;ve accomplished back when I was using QWERTY. This experience may provide inspiration and confidence for the improvement of these three skills because I will undertake a similar challenge and should expect similar results if all goes well.</p>

<h3>Impulsiveness - How Likely I Am To Put Off The Task</h3>
<p>Nick Winter describes low impulsiveness as &ldquo;At any time, there&rsquo;s only one clear thing that you want to do.&rdquo; Live streaming my progress somewhat solves the issue...by live streaming, there&rsquo;s only one clear thing that I must do (or else show my failure through the live audience) but it doesn&rsquo;t necessarily mean that I won&rsquo;t have problems focusing on it. In other words, I may not want to do the task but I will want to not <em>not</em> do the task.</p>
<p>A potential solution I can think of is a strategy that Thomas Frank used to keep distractions at bay. Whenever a curious thought or a temptation for distraction came into his head, he would write it down for dealing with later. I think this strategy has the potential to be effective because it takes the focus off of the mind (knowing it will be dealt with later) while still being in the midst of distractions. It will most likely be impossible to completely remove any distracting thoughts, but by putting them off to the side and using less effort than what would have been needed for eliminating them may prove to reduce the impulsiveness and increase my motivation.</p>

<h3>Delay - How Far Off the Reward Seems To Be</h3>
<p>Hyperbolic discounting is the process of valuing a task less from how far off in the future the rewards of the task lie. For example, you value a dollar more if it were given to you now than a dollar a month in the future.</p>
<p>I&rsquo;m scared of hyperbolically discounting the end result of this whole challenge. I&rsquo;m afraid the final reward being a month away may work against me and lower my overall motivation with this challenge.</p>
<p>One way I&rsquo;m tackling this issue is with the progress tests every week. I hope that these progress tests will give me quicker and more frequent gratification. Nick Winter described a low delay as always being near a goal&rsquo;s completion, thus never lacking the motive to finish something. By setting smaller but more frequent goals, I can look forward to each goal and get motivated by small success that can turn into a success spiral and bring me excess motivation. I may choose to aim for a specific WPM goal for the speed-measured skills I wish to develop for the weekly progress tests. This may motivate me more than if I chose to set one large goal for the whole challenge, which may end up becoming hyperbolically discounted to virtually nothing by the time a week passes by.</p>

<h3>Consequences</h3>
<p>I&rsquo;m still debating a bit with how I&rsquo;m planning to use consequences other than the guilt I receive post-pre-commitment. I may incorporate financial punishment with live streaming or use a tool like Beeminder.</p>
<p>I&rsquo;ll admit, I&rsquo;m a bit weasely when it comes to consequences. I&rsquo;ve lost $20+ on Beeminder which makes me hesitate to start trying it again. I&rsquo;ve also noticed that I haven&rsquo;t been practicing piano a lot lately compared to the 2 hours I would play every day in order to avoid paying $5 to Beeminder.</p>
<p>While consequences can prove to be a useful tool, you still want your motivation to be stronger than your fear. As Nick Winter puts it, you want to set up your mindset around the idea of &ldquo;enjoying the experience&rdquo; instead of &ldquo;surviving the torture.&rdquo;</p>

<h2>Planning</h2>
<p>Nick Winter managed to do a ton of things by making a plan...detailed to the very minute. This is one of the ways he was able to become successful in all that he aimed to accomplish. I love making plans as well...but the issue (perhaps a weak excuse) is simply the fact that there are too many exceptions in my day. These range from variable times (such as times for the three meals of the day), to unexpected mandatory events (which for whatever reason occur quite frequently), to underestimating the time it takes to finish a session.</p>
<p>My solution to combat this issue will be dedicating a whole day for reflection and planning. My summer school session only runs from Monday - Friday (the days I am expected to be online for 6 hours) and plan to finish everything unfinished by Friday on Saturday. On Sunday, I plan to reflect on the past week and create a self-reflection on what I did well, could&rsquo;ve done better and will do next time. I think reflection periods like these are extremely important for effective plans. I will also be planning out the schedules of Monday - Saturday as precisely as possible to maximize the time and preparedness for undertaking my challenges.</p>

<h2>Extra Time</h2>
<p>It will be inevitable that I will have some time left after finishing everything related to summer school. I plan to use this time to prepare for my SBS focused on computer algorithms. More specifically, I plan to attain a basic understanding of a pre-requisite I currently lack: calculus. I&rsquo;ve looked through the concepts of the main algorithm textbook and found that it requires some knowledge of calculus. As such, I plan to learn as much as I can during the extra time I have available during the summer school course to become better prepared for August, the time of the SBS.</p>

<h2>Potential Problems</h2>

<h3>Streaming Complexities</h3>
<p>Many complexities arise when I choose to stream &lsquo;my homework&rsquo;. The largest problem is exposing myself to plagiarism, which I don&rsquo;t tolerate. Even though I am near certain that nobody enrolled in my course can read Gregg Shorthand, it&rsquo;s still important that I take every precaution to prevent even the most unlikely situations. With Gregg Shorthand, I&rsquo;ll simply be writing with a pencil while filming in a resolution that does not allow the text to be fully legible. It will be a bit more difficult to hide the text of my Esperanto write-ups, but I do plan to only show a portion of the document and stream myself typing with the left hand (which I can assure will be impossible to copy from because of the fingers blocking the keys I&rsquo;m typing as well as the fact that I&rsquo;m not typing on the QWERTY layout).</p>
<p>The other issue with streaming this topic is fairly evident: people don&rsquo;t care about my homework. They are likely not interested enough in what I am doing to watch it for 6 hours a day. My response to this issue is simple: accountability doesn&rsquo;t have to be popular. It simply has to provide a potential for people to check up on your progress. People don&rsquo;t have to watch me for 6 hours straight to provide accountability. Accountability is provided by the simple fact that it is possible for somebody to check in and see what I am doing at the moment. This will motivate me to stay on task because of the knowledge that there is <em>potential</em> that somebody could witness me failing my challenge.</p>

<h3>Course Complexities</h3>
<p>I was exploring the online classroom environment when I found that quizzes can be timed. In other words, a test may have a countdown clock that won&rsquo;t consider my challenge. In these cases, I either have the choice of committing to my challenge and risk failing or give up temporarily on the challenge.</p>
<p><strong>Update:</strong> After attending the orientation and asking this very question (&rdquo;will there be timed tests?&rdquo;), I&rsquo;ve discovered that the answer is no. The majority of the marks will stem from a few major assignments, which allow for the potential to stick with my plans. However, there will be live classroom &lsquo;meet-ups&rsquo; that may demand the use of typing up questions or other immediate responses. For the most part, I will stick to typing them in left-hand Dvorak (in English, of course) without preceding them by my writing of Gregg Shorthand. When the time is immediate, I will resort to typing with both hands.</p>
<p>The assignments will involve the usage of the three goals. They are also worth most of the marks for this course and luckily are deadline-based and not time-based (assuming I don&rsquo;t procrastinate). I do seek to do well in this course, but my motive leans more towards a solid development of a useful skill set.</p>

<h3>Temptation to Quit</h3>
<p>Scott Young undertook a similar challenge with his &ldquo;Year Without English&rdquo;. He committed to only speaking a certain language when he entered the matching country. In the end, he could speak four languages well enough to hold a conversation. This strategy was effective because it forced Scott to use the language no matter how difficult or cumbersome it was. Google Translate and language dictionaries quickly became his best friend. In his TED Talk about this subject, Scott mentions how there&rsquo;s a barrier between true immersion: the fear of making mistakes. By getting across this fear, you start effectively learning the language you wish to learn without being held back by negative responses.</p>
<p>My barrier isn&rsquo;t so much fear as it is frustration. I definitely feel extremely limited and frustrated typing at 20 WPM with my left hand instead of my usual 100 WPM with both hands. Writing at 20 WPM is also much more frustrating than writing at my normal speed, not even including the fact that I&rsquo;m writing down text I plan to type after.</p>

<h1>Final Thoughts</h1>
<p>At the end of all this planning and forethought, the number one most important part of this whole challenge is to not give up.</p>
<p>Even if I struggle through thousands of eraser crumbs and have to use a dictionary to translate every single word in Esperanto, doing so is infinitely better than submitting to the ease of comfort.</p>
<p>This challenge is for breaking my bubble of comfort and for pushing me to develop skills in a quick nuclear that will make me suffer.</p>
<p>Suffer is only a term for the weak. Withstand is what I must do.</p>
<p><em><strong>&ldquo;A life without challenges isn&rsquo;t worth living.&rdquo;</em></strong></p>

<p><strong>P.S.</strong> Streaming times and other accountability information (if you&rsquo;re actually interested) will be posted on my Twitter profile <a href=&rdquo;https://www.twitter.com/leonzalion&rdquo;>(@leonzalion)</a> and will be incorporated into the new announcement feature coming soon. I will announce streams when they go live, but I can&rsquo;t guarantee specific streaming times. However, do expect around a stream a day!</p>
