<p><strong>Note: </strong>Hey, this article might seem a bit rushed...and truthfully, it was. I&rsquo;ve recently been busy working on my website design and school projects. However, I still wanted to provide something new and stick to my word of trying to get something out every week (even if it&rsquo;s at 11PM on Saturday). This article is about a topic that I could talk a lot more about and do plan to develop it as time goes by. However, time also hasn&rsquo;t been too kind over the weekly deadline I have to post this by, so I hope you can understand if this article seems a bit shallower and more rushed than usual.</p>
<hr/>
<p>This article was originally going to be a huge essay about defining what constitutes a video game. However, for the sake of getting my point across, I&rsquo;m going to simplify the definition of a video game in the simplest terms. To me, a video game is a form of entertainment in which productivity is hindered by the indulgence of interaction with a digital device.</p>

<p>The resolution I&rsquo;m debating is whether video games are a waste of time. I will be arguing for the affirmative side of this debate. Firstly, the definition of some terms in this resolution would likely be appreciated.</p>

<h1>&ldquo;A Waste Of Time&rdquo;</h1>
<p>&ldquo;A waste of time&rdquo; is a pretty broad statement. I will define &ldquo;a waste of time&rdquo; as an entity that takes time and does not proceed to output enough benefits to give worth to the use of such time. Of course, giving enough worth to validate a non-wasteful state is subjective. This holds the true heart of the topic at hand: whether playing video games is worth enough to give it a non-wasteful state; whether video games output enough benefits to justify the time used indulging in video games.</p>

<h1>Providing Reasons</h1>
<h2>Video Games are Addicting</h2>
<p>&ldquo;Anything in excess is harmful.&rdquo; That is an undeniable fact, for an excess of anything is itself defined as having such an amount of something where it would qualify as &lsquo;excess&rsquo; and therefore qualify the whole as a negative influence. A waste of time is implicated in this property of video games because, in order to play video games, one must sacrifice time. The issue is with video games, the interactive component seeks to obtain large amounts of time until its user has satisfied their wishes for amusement. <a href=&rdquo;https://bgr.com/2014/05/14/time-spent-playing-video-games/&rdquo;>The average time spent playing video games for people who play more than 5 hours a week is 22 hours...per week.</a> Notice how the threshold for filtering out non-frequent gamers ends up revealing that people spend either only a little or a lot of time playing these video games. This demonstrates that video games have the power of turning those &ldquo;only for 30 minutes&rdquo; remarks into time-killers lasting for hours. This statistic shows how video games have the risk of stealing a lot of your time even when exposed to a little, i.e. that video games are dangerously addictive.</p>
<p>Of course, to justify that the addiction to video games is tied with their being a waste of time, one must argue why they are a waste of time in the first place. However, acknowledging that the properties of video games make them addictive is a step further in realizing why they are harmful in terms of productivity and efficiency.</p>

<h2>Video Games are Distracting</h2>
<p>Of course, we can all agree that when we think of video games when we work, we&rsquo;re less productive than if these thoughts weren&rsquo;t floating around in our heads (unless you somehow got involved in doing a project about this video game). Known as attention residue, the distracting afterthoughts from a video game can be detrimental to one&rsquo;s productivity and efficiency in getting a task done. Attention residue becomes stronger when our reward is cut short (e.g. we are forced to leave our video games for motivations other than to deliberately want to stop). Due to the (sad?) fact that most of us don&rsquo;t really end up leaving the console with our own will and a feeling of satisfaction, attention residue strikes us by hacking away at our motivation and eventually causing us to topple into a state of low productivity (which then introduces the risk of greater distractions, such as watching YT on a device or other low-intensity fun).</p>

<h2>Video Games Build a Poor Mindset</h2>
<p>One of the most enerving mindsets I come across is that something needs to be fun to be worth indulging in. Of course, this is why games built upon the goal of making education fun exist and are widely promoted throughout elementary schools. The reason for this increase is the simple fact that society is encouraging this mindset of &ldquo;you can make anything fun.&rdquo; The truth is, you really can&rsquo;t. There&rsquo;s a point where fun takes away from efficiency and even effectiveness. When you start promoting the toxic mindset that you can incorporate fun into anything to &lsquo;make it worth doing,&rsquo; you start creating a less effective society in the long run.</p>
<p>What do video games have to do with this? Well, by justifying the playing of video games, we promote this mindset. We promote that &lsquo;life can consist of just fun and games&rsquo;. By hiding the truth from children (the truth that those who walk through the hard part of life are those who enjoy it the most), we start allowing people to develop an unhealthy craving for entertainment. We start undermining the importance of genuine study by allowing video games to be acceptable.</p>

<h2>Video Games Damage Your Eyes</h2>
<p>There&rsquo;s the 20-20-20 rule that we all should follow when using a computer. However, because of the high-intensity of video games and the number of activities that are going on at a time, we often forget about this rule. Even with reminder programs (and I&rsquo;ve experimented with this), you often justify yourself postponing it until your eyes go red. Not only do we often weasel out from the 20-20-20 rule during our playing, but we also don&rsquo;t tend to take breaks, especially with friends that don&rsquo;t. When I succumbed to this toxicity over the March Break, I ended up playing video games for 9 hours because of a friend on the other side who simply didn&rsquo;t care for taking breaks. If it was solely me who was playing, I wouldn&rsquo;t have played for such an extreme amount. This point ties back with video games being addictive. Combining this fact with the damage they can cause to your eyes can show a really disastrous consequence for a stupid addiction.</p>

<h2>Video Games Promote Poor Values</h2>
<p>If you are subjected to the same kind of behaviour day-by-day, it&rsquo;s likely that you will end up following this behaviour. As such, if you play the same video games day-by-day, you start to justify your behaviour based on the actions in the video game. The question of whether video games really cause violence is still being debated. However, it is very much true that a child growing up in a poor environment (in terms of morality and behaviour) greatly increases the chance of the development of these bad values in the child. As such, growing up with video games promoting immoral activities and behaviours would eventually get to a child&rsquo;s head and make them more prone to not condemning or even approving of these objectively immoral acts.</p>

<h2>Video Games Destroy Motivation</h2>
<p>I&rsquo;ve recently experienced this situation first-hand. It started when my friend came over and we had absolutely nothing to do, so we just ended playing video games. The issue was, this was only supposed to be a temporary solution so that he didn&rsquo;t die of boredom before he had to leave. After he left, I started to lose motivation to do any work and ended up wasting an incredible amount of time on time-wasting applications (interestingly enough, these applications actually didn&rsquo;t include video games themselves). If it weren&rsquo;t for my choice to take out a video game, I&rsquo;m sure that I wouldn&rsquo;t have lost so much time because of the hit I took to my motivation from it. Of course, this doesn&rsquo;t necessarily mean that. How would I know that it was video games that caused this problem? Well, this wasn&rsquo;t the only time where I ended up having a productivity crash after a video game. Every time when I make this bad decision, I always end up with its post-consequences. As well, playing video games does sap your energy. By focusing your effort into playing in a virtual world, you start losing the reality check in your own. In doing so, you start fading away from your real responsibilities and duties that will follow you in the real world regardless of how long you decide to escape from there. In other words, playing video games worsens the connection between you and what you still have to get done by acting as an escape route. Once you&rsquo;ve entered, it&rsquo;s very hard to turn back and get back on track. If you still don&rsquo;t believe me, try doing an SSS while allowing yourself to play some video games and tell me how it goes (maybe it may be that I&rsquo;m not used to playing them and my brain can&rsquo;t handle leaving reality...)</p>
<p>Of course, it&rsquo;s evident how this ties back in with wasting time. By causing a decrease in productivity after you&rsquo;ve played the video game...you get less done. It&rsquo;s pretty self-explanatory.</p>

<h2>Time Flies Playing Video Games</h2>
<p>Usually, doing anything fun will cause the time to fly. However, playing video games poses a much greater risk of this &lsquo;phenomenon&rsquo; because of how it is designed to be playable for hours on end. Video games are designed with this very purpose in mind. The most popular ones are designed to never end and can be enjoyed for quite a long time with you losing track of how long you&rsquo;re playing for. Because of this design, unless you play for an extreme amount of time or your body/mind is begging you to quit (from strained eyes, mental tiredness), you&rsquo;re bound to play for an indefinite amount of time and will always leave you wanting more. This ties back with another reason why they cause a mental &lsquo;depression&rsquo; after you&rsquo;ve played them. As such, if you&rsquo;re bound to lose track of time doing an unproductive activity, it not only makes video games an utter waste of time, but also an actual risk of swallowing up your time as well.</p>

<h1>Defending Arguments</h1>
<p>Of course, no side of a debate would be persuasive if they didn&rsquo;t answer to the points of the opposing view. As such, I&rsquo;ve gathered some prominent points that portray benefits of video games and will continue to explain why these benefits don&rsquo;t necessarily merit video games the title of &ldquo;A non-wasteful time&rdquo; activity.</p>

<h2>Video Games May Slow Down Aging</h2>
<p>The opponents claim that video games are crucial to keeping the brain active. They relate it to exercising the brain and claim that this will slow down aging. However, there&rsquo;s one fallacy in this argument. It isn&rsquo;t the video games themselves that give the reason for this consequence. Rather, any task that needs the exercising of the brain will keep it sharp, including...you guessed it, doing actual productive work.</p>
<p>If we acknowledge that the time spent playing video games could be used in a more productive way (learning) while still reaping the benefits of slowing down aging (as learning is an active activity), then one can deduce that video games are in fact, not worth the benefit of slowing down the aging process and would be considered as a waste of time because the time could be used in a more productive manner while bringing more to the table at the same time.</p>

<h2>Video Games Can Help You Make Better Decisions</h2>
<p>&ldquo;Action video games are fast-paced, and there are peripheral images and events popping up, and disappearing. These video games are teaching people to become better at taking sensory data in, and translating it into correct decisions.&rdquo; - Shawn Green, a comment on results from a study where a group of young adults with no gaming experience played an action game for 50 hours. To explain why this benefit of video games still does not make it worth indulging into, one must realize that improving decision-making does not mean just translating sensory data into decisions relating to the best choice for the data. For one, choosing to play video games in the first place is already a poor decision in virtually every scenario, so that&rsquo;s already a step backward. One demonstrates good decision-making when they make good choices and I can definitely say that we don&rsquo;t play video games because we want to train our art of making good decisions. Rather, we play because we don&rsquo;t want to do something else (often of a higher priority) and use video games to escape from this reality, already having chosen to follow through with a poor decision.</p>
<p>Now, what about the decision-making benefit of turning sensory data into decisions? The issue with this claim is, the activity in which we wish to use this ability (or changing/reacting to events and making decisions based upon them) is almost always more prevalent in building this skill. For example, if I wanted to improve my decision-making in a sport, playing the sport and practicing real-life scenarios of the actual sport will inevitably provide the player with more training in decision making than playing video games would. The claim that video games boost reaction time, in general, is also bogus because anything that trains your brain to react quickly will help your brain do just that; the benefit of decision making from sensory data is not unique to video games. Thus, the claim that video games improve decision making doesn&rsquo;t allow it to be exempt from its consideration as a waste of time.</p>

<h2>Video Games Can Help Your Eyesight</h2>
<p>Of course, playing video games does damage your eyesight because it has been prone that we tend to blink less when viewing a screen, which is a fundamental part of video games. However, recent studies have demonstrated that &ldquo;[p]laying action games improves an ability called contrast sensitivity function.&rdquo; - Daphne Bavelier, leader of a study where a group of experienced gamers played first-person shooters while casual gamers played slow games like The Sims 2. Contrast sensitivity function helps distinguish between different shades of gray against a coloured background, which can benefit in dark situations such as driving at night.</p>
<p>Rebuking this point is pretty simple. <strong>Video games are not the only (nor the best) way of improving contrast sensitivity function.</strong> Anything in general that involves fast-paced reactions would improve one&rsquo;s contrast sensitivity function...including tests designed for improving this very function in general. As well, virtually nobody plays video games for the benefit of their eyes, for the addictiveness and binge playing will cause way more harm to one&rsquo;s eyesight in the end. If you have a problem with your eyesight where you cannot distinguish well between similar colours, you can&rsquo;t just tell yourself that you can play video games and get away with it. Instead, you will need to get specialized glasses, take tests that actually are made to improve this function regularly instead of indulging in video games and declaring it as medicine, an invalid excuse for giving it a non-wasteful state.</p>

<h2>Video Games Can Make You More Social</h2>
<p>Studies have shown that &ldquo;gamers who partake in live social environments are actually the most communicative and friendly people there.&rdquo; Therefore, one can argue that by playing games, you become more sociable. Evidently, that&rsquo;s not 100% true. An introvert doesn&rsquo;t just download Fortnite and become the most extroverted person at the next party they go to. If you really want to become a friendly and communicative person, you should train yourself to do so without the need to talk about games. Games are especially addicting with friends. By basing a friendship off of playing games together, this friendship is not beneficial to you nor your friend in terms of actually having a genuine friendship where you can actually socialize about topics not involving games. These friendships are unhealthy because it ends up breaking when one person discovers that playing video games would not be beneficial for them (e.g. they want to get good grades, want to go outside more, etc) and would end up breaking this fragile friendship. Even worse, humans are designed to resent breaking up relationships. This can lead to one developing an unhealthy habit for playing video games with friends and make it hard for them to decline because they&rsquo;ve developed a strong (but unhealthy) friendship through playing games with others. This will inevitably cause them to waste time on a poorly connected relationship that won&rsquo;t benefit anybody in the long term. In the end, if you want to make friends, make friends with the intent of benefitting from more than just getting entertainment out of it.</p>
<p>Now, to counter the claim that video games make you a more sociable person in general, we need to realize that sociable does not mean they are a good friend. Obviously, we don&rsquo;t want to be friends with people who can&rsquo;t use/maintain friendships properly. If you really want to be able to create good and long lasting friendships, you should get out of the basement and learn how to make good friendships instead of being that person who plays the same video games as you do and basing a friendship off of that. The video games you play often does not reflect your personality. By basing a friendship off people playing the same video games, this wouldn&rsquo;t benefit anybody in the long run unless these people are coincidentally similar in other interests more useful than video games. If you want to build friendships off of similar interests, choose an interest that can actually benefit both sides of the friendship instead of just having entertainment together. Friendships should be more than just a tool for entertainment.</p>

<h2>Video Games Can Help You Learn</h2>
<p>Interestingly, one can argue that a video game can help one learn. Is this enough to justify playing it so that it isn&rsquo;t a waste of time? No. Unless you&rsquo;re playing a game and deliberately learning something from it as your main goal (e.g. an educational game, more on that later), the side-benefit of education from the main purpose of entertainment is not enough to justify playing it. A study was conducted where people played Starcraft for 40 hours over the course of a month and a half to two and they found that these players gained better cognitive flexibility (being able to switch between thinking about 2 different concepts or thinking about multiple concepts at the same time). However, taking the time to play video games and justifying yourself in terms of &lsquo;boosting mental brainpower to work on future tasks better&rsquo; is objectively not as efficient as simply doing the task that playing video games is hindering you from doing. This is because there&rsquo;s a limit to how much one can improve before the improvement starts turning logarithmic. Also, you can&rsquo;t multi-focus. Don&rsquo;t believe that you will be able to once you play enough video games (read my &lsquo;Multitasking&rsquo; article for more information about that).</p>
<p>I&rsquo;d like to expand on video games for education. I know of many applications that can help you learn that most people would consider being a video game. I&rsquo;m not saying that video games aren&rsquo;t helpful, but rather a waste of time. Learning a subject from a video game is...for the most part, a waste of time. Firstly, it&rsquo;s not good to depend on entertainment in order to learn, for that is a mindset that will greatly hinder you and end up wasting a lot of time in your life. Secondly, the purpose of these video games is to introduce one to a subject in a fun manner. If I shoved a 1000-page textbook on JavaScript in front of a Grade 4, it&rsquo;s likely that he wouldn&rsquo;t really be interested in learning it. However, if I were to introduce them to a video game such as CodeCombat that teaches the same material (although definitely not as thoroughly), they are much more likely to start developing an interest in this topic. In this case, I wouldn&rsquo;t consider video games a waste of time because making someone <em>want</em> to learn something through the power of video games will end up being more efficient than forcing them to learn. However, trying to learn by only playing video games will not be efficient and would eventually become a waste of time such that playing video games is not justifiable to the entertainment aspect of it.</p>

<h2>Hand-Eye Coordination</h2>
<p>This is one of the most prevalent reasons for playing video games. To be honest, all you need to say to shut it down (for 99% of these debates) are &ldquo;When have you ever needed proper hand-eye coordination?&rdquo; and then following up with &ldquo;then do that instead of playing video games.&rdquo; For example, if you told me that you need hand-eye coordination for golf, then I can tell you play golf more. If you can&rsquo;t play golf (because it&rsquo;s too expensive, etc.), then do activities that actually improve your hand-eye coordination that actually help you in other ways (e.g. activities specifically designed to improve one&rsquo;s hand-eye coordination that will be more efficient in doing so, doing an activity that you had (or should&rsquo;ve done) anyways that improves hand-eye coordination in the process, etc.). Rebutting this argument is pretty similar to rebutting the one about improving your eyesight: if you wish to reap these benefits, deliberately do something that was designed to increase these functions in the first place.</p>

<h2>Improved Focus and Attention</h2>
<p>Video games can help you pay better attention. According to experiments conducted by Vikranth Bejjanki and a few of his colleagues, he discovered that gamers did better on tests such as pattern discrimination and other tests demonstrating a more active brain. As such, they concluded that playing games can reap several rewards, paying better attention included in the set. This does still not warrant video games a get-out-of-jail-free card. If you want to focus better, it&rsquo;s more effective to just give up games together instead of playing games in order to get a better focus. Games leave behind attention residue, which means that people tend to think back about the game, especially when their reward was cut short (e.g. they were forced to stop playing instead of choosing to stop to play). Attention residue can greatly distract from the task at hand, meaning video games actually don&rsquo;t increase enough focus and attention as one might think. They may improve your cognitive processes, but in the end, there are many other productive things that can match (e.g. active studying, active reading, etc.), or even surpass these cognitive improvements from video games.</p>

<h2>Video Games Can Help With Depression</h2>
<p>SPARX is a video game with the intention of providing therapy that&rsquo;s more fun than traditional counseling. For me, this type of video game wouldn&rsquo;t really be considered a waste of time if it can manage to cure depression faster than counseling would. After all, you&rsquo;re probably wasting a ton of time in a depressed state, so your number one priority would be to get out of this state. However, if you&rsquo;re depressed and seeking entertainment from video games, or if video games aren&rsquo;t making you any less depressed and you still play them, they would still count as a waste of time because they aren&rsquo;t benefitting you in any long-term way. I do respect video games that can help with conditions and speed up a process, but I don&rsquo;t respect when ties are made to these kinds of video games from intentions of mainly entertainment and amusement purposes.</p>

<h2>Video Games Provide Exercise</h2>
<p>Going outside provides exercise. Seriously. If you give me this desperate point, I&rsquo;ll respond with the advice to get off your couch and go sign up for a gym membership.</p>

<h1>How can one stop?</h1>
<p>The longer the time between now and the last time you did something, the less likely you are too long for it. Using this rule, knowing that the longer you&rsquo;ve left video games behind, the less likely you are to indulge in the bad habit.</p>
<p>You&rsquo;ve probably found out by now that the strategy of playing video games until you get bored of it doesn&rsquo;t really work. Video games are designed to not get boring. However, if you can choose to deliberately get bored from them (e.g. make playing it frustrating, deliberately making it hard to get to them), then you can have a greater chance of destroying this bad habit.</p>
<p>A big motive in playing video games is simply having nothing else to do. Playing video games to pass the time is the worst mindset you can have. If you have extra time on your hands, use that time to do more productive things. You can challenge yourself to do something, and don&rsquo;t just say it and act like it&rsquo;s done. You should work hard at what you want to do. The truth is, we never have extra time that can&rsquo;t be used. There is always something worth our time such that playing video games would almost never be the best use of it. We find passions by working on them. They don&rsquo;t come to us by magic. If you truly wish to live a good life, then you should have to step back from the pleasures of one.</p>
<p>Another scenario in which I tend to play video games is when my friends come over. I feel extremely guilty boring them to death with nothing to do (especially when we don&rsquo;t share common interests), so I usually turn to video games as a last resort, because who doesn&rsquo;t like video games? (Honestly, today I found out that I actually can&rsquo;t play video games because I constantly feel like time is being wasted as well as feeling completely dead inside and just terrible in general). Obviously, I know I could&rsquo;ve found a better activity to do that could also count as being productive, but I guess I was scared of letting them get bored and turned to desperate measures. Of course, I&rsquo;m sure you&rsquo;ve been in a similar situation, and I would advise you not give in to video games unless they really want to (in which case, try not to feel guilty about playing it and make sure that your friendship isn&rsquo;t built too strong upon on video games). Look beyond the present (making your guest not bored) and seek to understand the bigger picture (developing a strongly bonded friendship) and work towards the bigger goal. In other words, don&rsquo;t feel guilty about letting them get bored. Instead, try your best to develop the friendship in some other meaningful way that allows both parties to get something far more useful than shallow entertainment.</p>
