<p>Group projects are infamous to those who care about marks and refuse to act as a freeloader of a group.</p>
<p>You will probably fail in evading group projects during your academic career (or even your career further down the road, for that matter). Group projects exist to practice an extremely important skill: cooperation. Unless you plan to live in isolation, cooperation is a skill that you must master if you wish success upon yourself.</p>
<p>The truth is, cooperation is a lot harder to achieve than one might expect. We all want to believe we are right, which is the very factor that causes a spirit of cooperation to crumble and fall. If given the choice, everybody would want to follow what they believe is right instead of what the bigger picture recommends. This is the portion of the group project that makes it a much more daunting task (for some people...) than an ordinary individual project.</p>

<h1>Group Members</h1>
<p>There are two main ways groups are chosen: by the groups or by the project&rsquo;s assigner.</p>
<h2>Choosing Your Members</h2>
<p>Unless you have abnormally cruel teachers for your entire academic path, a teacher is bound to let a group choose their members. For the most part, most groups are based upon external friendships and not really based on who would work the best together (because we must admit that working with our friends, depending on the people, isn&rsquo;t always the optimal choice). However, I&rsquo;m not advising against choosing friends to work with you, but I am advising against choosing friends for the sake of friendships. If you cannot trust a friend to work together with you without being a distraction and hindering the working process, it probably would be wiser to search for a different group member to fill his spot.</p>
<p>There is one evident benefit with working with friends: ease of communication. For the most part, friends have easy access to communication with one another and will be motivated to not let their fellow peers receive a bad mark because of them. They will strive to try their best to make sure that nobody slacks behind and will help them if they can. This communication can also become an issue as well. From both observations and personal experience, friends tend to lose focus on a project if they are informally working together (through an impulsive group chat compared to a formal meet-up at some place). Again, this all comes down to making sure your friends are people whom you would want in a group for success rather than for friendship.</p>
<p>If possible, aim to achieve a diverse skill set within the members of the group. If your project is to present a play and you create a group with all introverts, you probably shouldn&rsquo;t get your hopes up for a smooth presentation. Even one extrovert who can improvise well on the spot will act as the glue that makes sure the group doesn&rsquo;t fall apart. Make sure that your group contains a glue (e.g. the leader) that makes sure the project doesn&rsquo;t fall apart.</p>
<p>If you&rsquo;ve already made a group that realizes that none of the members can fulfill a specific part of the project well, don&rsquo;t fear! Another way to handle this problem is by making the project work for your group. For example, if you&rsquo;ve ended up with a presentation where all members are introverts and there exists the option of recording the play instead of presenting it live, use that to your advantage. Or, if you aren&rsquo;t given such an option, you can try other ways such as making the play equally dependent on all three members (e.g. not just one person asking all the questions) so even if one person forgets their line, the show can still go on!</p>
<h2>No Freedom of Choice</h2>
<p>You are inevitably going to be faced with a random group assigned to you. Usually, the groupings of these groups have an ulterior motive (e.g. pairing the students who are succeeding with the students who are struggling), but there will the occasion where names are picked out of a cookie jar.</p>
<p>No matter how the groups are chosen without your say, you may end up with unmotivated group members and members who don&rsquo;t care for the project&rsquo;s success. By your reading of this article, I assume that you&rsquo;re probably not one of these people and wishes a good grade for the group (and you!). I&rsquo;ll dive deeper into this topic in the &ldquo;Being a Leader&rdquo; section, but I can say that you will have to dedicate extra effort in keeping the group organized.</p>

<h1>Focus on the Bigger Picture</h1>
<p>The bigger picture of a group project is the final result. Before starting a group project, one must ask themselves this very question: &ldquo;What is the purpose of this project? Why does it exist?&rdquo; This question is extremely important because for the most part, if your group can show that this project helped you in some way and can prove it to the person who assigned it to you, you will most likely be rewarded, for you&rsquo;ve fulfilled the very purpose of the assignment. For example, a group project to present a play in French would center its focus around practicing one&rsquo;s oral skills in French. As such, the bigger picture aims to demonstrate these oral skills to the best of their potential and your focus should revolve around this point.</p>
<p>For the most part, the main purpose of a group project is to solidify an understanding of a subject or material collaboratively. A group project seeks to allow more knowledgeable members to interact and share their knowledge with less knowledgeable members while further testing and strengthening their own familiarity on the core material. Yes, group projects (usually) don&rsquo;t waste the time of even the members who don&rsquo;t seem to need help. They are built on the learning pyramid showing one&rsquo;s actively learning from explanation can inscribe an understanding deeper than from passively reading and listening.</p>
<p>Once you&rsquo;ve identified the larger picture, build your goal from there. It sounds a bit strange to go from the end to the start. However, the core importance of the group project is to make sure everybody&rsquo;s motive is centered on one thing. Having identified this motive (the bigger picture of the project), the group can now build from this idea and find ways to demonstrate the understanding of this big idea. Building upon the French presentation example, we can imagine that a group would create a script that focuses on being morally complex and fulfilling the motive to the best of its potential. As such, instead of struggling to find ways to show off your oral strength from a topic, you find a topic that would demonstrate your oral strength from being a suitable topic for your project&rsquo;s purpose. Relating back to the French example, if you wished to use multiple tenses in your performance to show off your knowledge of tenses and when to use them, you would select a plot where it is easy to relate to relevance in the past, present and future (e.g. an event that you&rsquo;ve once been to, going to at the moment and planning to go in the future).</p>
<p>Planning from the bigger picture doesn&rsquo;t ask &ldquo;what to do next?&rdquo; but &ldquo;what to have done before?&rdquo; This allows for a much easier analysis of a large project and can greatly help with reducing it to smaller and more manageable pieces. This tactic is especially useful for main ideas that are vast and vague while still providing help to even more specific topics. As one of the best ways to handle a group project is to break it down to simple steps that can be evenly distributed to the group members, using the tactic of &lsquo;starting at the end and ending at the start&rsquo; can allow for a much more efficient process.</p>

<h1>Distributing Work</h1>
<p>With every group project, a challenge the group faces is distributing the amount of work needed to achieve a final result amongst its members. Randomly assigning work wouldn&rsquo;t really be the most effective (nor efficient) way of handling the dilemma of work distribution. Below lies some popular methods of work distribution that come with their ups and downs.</p>
<h2>Evenly</h2>
<p>Distributing work evenly should be one of the main focuses of work distribution, but not to the extent where it would override the more efficient method of distributing wisely. The effort and time one needs to put into work are subjective. Trying to objectively split work amongst members in terms of constants (e.g. the time it would take, materials it would consume, etc.) is often not the most effective way. Of course, fairness should be valued in any group project, but not to the extent of forcing inconvenience upon a group member for the sake of being as fair as possible. For example, if a group wanted to meet up for working together on the project and one member couldn&rsquo;t show up, giving extra work to the member who missed the meeting for the sake of being fair wouldn&rsquo;t really be...fair.</p>
<p>Work in a group project doesn&rsquo;t just include time and effort, but often material as well. As well, evenly distributing material contributions shouldn&rsquo;t value fairness over logic. For example, if a project required a prop that somebody already possessed, that person should use their prop (given it wouldn&rsquo;t need to be damaged or permanently changed to their disliking) even if it would&rsquo;ve been more &lsquo;fair&rsquo; for another member to bring in a similar prop when they would need to purchase/create one.</p>
<h3>Based on Skill Level</h3>
<p>Another suggestion to distribute work as efficiently as possible is by skill level. In other words, give the more advanced work to the people that can handle this more complex work and leave the more lenient work to those who struggle to take on more demanding tasks, both in effort and knowledge. After reading the section on focusing on the bigger picture, I hope you can understand why distributing work in this manner has the potential to be ineffective when it comes to the project as a whole. Basing work off the level of knowledge does not benefit either party (the more knowledgeable part and the less knowledgeable part) in the best way possible when it comes to learning the material. By assigning the group members who need the most help on the subject the least demanding work, you start overlooking and outright ignoring the intended purpose of a group project in the first place: solidifying a topic&rsquo;s understanding in a collaborative effort. A group benefits more from one &lsquo;smart&rsquo; person and one &lsquo;less smart&rsquo; person working together than it does from two &lsquo;less smart&rsquo; people or two &lsquo;smart&rsquo; people. The &lsquo;smart&rsquo; person solidifies their understanding by explaining the concept (which is what you&rsquo;re required to do on a test) while the &lsquo;less smart&rsquo; person benefits from being taught and being given attention by one who understands the topic that they&rsquo;re struggling with. Having the &lsquo;less smart&rsquo; person active work with the &lsquo;smart&rsquo; person in an attempt to learn about a subject they originally found difficult to grasp will most likely benefit them more than if they just tried learning the subject on their own. To sum up, basing work on skill level would be efficient, but only effective if the group members make an effort to make sure that the whole group understands each other&rsquo;s research and subtopics and strive to teach their understanding to one another.</p>
<p>There&rsquo;s another aspect of skill level that is used in a group project: the skills that are irrelevant to the fundamental purpose of the assignment. For example, having skills in using PowerPoint efficiently doesn&rsquo;t contribute to a better understanding of the material and as such should be used to its full advantage. If a skill would improve the project&rsquo;s execution while minimally affecting the effectiveness of the project&rsquo;s original purpose, it should be used to its fullest potential to improve a project&rsquo;s efficiency. In a presentation project, the member who is the most comfortable presenting should often be assigned most &lsquo;outgoing&rsquo; character because they would be the best candidate for such a role.</p>
<h2>Based on Wants</h2>
<p>However true it may be that we are more willing to do what we want, it may not always be the best approach to take. Rather, it&rsquo;s important to look deeper and find out <em>why they want what they want.</em> Once you find the real reason behind their desires to take on a certain part of the project rather than another, it&rsquo;s your job to reflect on the validity of that reason. For example, if one group member wanted to do a specific part of the project because they didn&rsquo;t want to do a lot of work, that motive would be the wrong reason and would only lead to them not producing a reward that matches your standards. Instead, you want to give them a motive that focuses on giving them a reason to produce quality work, whether that would be making the part fun or lifting its importance.</p>
<p>There&rsquo;s also the &lsquo;lack of want&rsquo; when nobody wants to play a part or fulfill a major role. Usually, the leader steps up to this task because they are the one that will most likely work the hardest on this portion given that their wish success on the project is the firmest out the other members (considering they&rsquo;ve volunteered to be a leader). Unless it becomes evident that you&rsquo;re starting to take on too many roles that nobody else wants to do (in which case you should try either convincing or simplifying/making the roles more motivating), you usually should be willing to take on even the most boring/demanding parts of the project (either that or, as a last resort, changing the project plan in some way that requires less effort and often fewer rewards). There&rsquo;s also the (interesting) issue of having more than one person that really wants to play a specific role, which in that case you should try to either split up the role between the two members or if that&rsquo;s implausible, find the motivation for playing that role and try incorporating that same motivating factor into another role of the project. Persuasion and convincing should usually only be used as a last resort.</p>

<h1>Creating Motivation</h1>
<p>Motivation is a big part of any large project one wishes to tackle. However, it is especially crucial if one wishes to smoothly execute a plan for a group project. The issue is, a group project will inevitably depend on more than one person to finish their part. Likewise, the saying still follows; a chain is only as strong as its weakest link. If you fail to provide motivation for a group member to finish their part with care, you start entering a risky zone where the weakest part of the project takes away from the grander scheme. A flawless book is flawless because it does not contain a single flaw. Even one typo out of a million words can cause a great loss of respect from a book deemed mistake-free.</p>
<p>After burying myself in the works of Dale Carnegie, I&rsquo;ve come to realize that most of the actions that tend to motivate someone stems from giving them a feeling of importance. In other words, have your actions hint a subtle and sincere message that the project needs them to be a success. Examples include sacrificing time to work together (e.g. meeting up at a library or taking the time to voice chat and check up on one another), or bringing attention to the importance of their part (how essential their task is for the final project). As well, you need to make sure to emphasize how a successful group project would benefit them. It wouldn&rsquo;t be nearly as motivating if you tried to convince with citing &ldquo;because my average needs to stay high&rdquo; as the main reason for a wish for effort. Rather, you need to point out why they need to care about the success of the project (e.g. because it would help them gather a complete understanding of the material they are bound to be tested on, it would allow us to help them answer questions and prepare more thoroughly through ambiguities, etc.). Cooperation is meant to be unselfish. By using unselfish reasons to motivate your fellow group members who your mark heavily relies on, you not only give your group a higher chance of producing an amazing result but also work on improving your own critical skill of working with others.</p>

<h1>Being a Leader</h1>
<p>Every group will need a leader. It&rsquo;s as simple as that. Without a leader, a group would spiral into disagreements, lose progress and fall into entropy.</p>
<p>Being a leader, however, will demand more of your effort and time. To be a leader, you will need to be willing to make sacrifices and deal with the laziest of group members. As a leader, you will be mainly responsible for recovering from exceptions and lazy group members. You will need to stay committed, for the fate of the project will rest on your shoulders&mdash;</p>
<p>Relating a leader to a superhero is honestly quite a large jump. Being a leader isn&rsquo;t as difficult as you think. It will take more of your time, but then again, I assume you&rsquo;ve already got over that realization. The truth is, anybody can be a leader. It&rsquo;s only the good leaders that lead the group to great results.</p>
<h1>Being a <em>Good</em> Leader</h1>
<p><strong>To lead:</strong> to direct on a course or in a direction<br/>
That&rsquo;s your job. Your job is to direct your group members on the course to the final project. Assuming that you&rsquo;ve already got a picture of the final result as well as a plan to get there, your next job is making sure that you&rsquo;re group members understand these plans. I cannot stress that enough. <em>Make sure your group members know what they&rsquo;re supposed to be doing.</em> I&rsquo;ve already suffered enough group projects where a member had no idea what they were supposed to do and didn&rsquo;t put in the effort to find out. Enough guilt has been felt when I&rsquo;ve done everything in one part and find out that my other members thought they were supposed to do that part. And of course, we all have felt the frustration of &ldquo;I thought you were going to do that&rdquo;, said everyone ever.</p>
<p>The first step you want to take is to make sure you have a means of instant communication (not email but more like messaging). This way, if an emergency pops up or a deadline is approaching, you&rsquo;ll be able to get the message to the attention of your fellow group members right away and make sure that they&rsquo;re still on task. Of course, there will be the occasional group member that doesn&rsquo;t have any social life and lacks a means of instant communication (you&rsquo;re looking at one). In these cases, you&rsquo;ll want to either convince them to get one or if they aren&rsquo;t able to (or don&rsquo;t want to, in which case you&rsquo;ll need to motivate them), give them parts that don&rsquo;t require building on further down the project&rsquo;s execution (give them the job of making the cherry and not the cone). This way, you don&rsquo;t need to worry about one part that cannot be done because they didn&rsquo;t send you their finished product.</p>
<p>You need to lead your group <em>away</em> from entropy. You need to organize everybody&rsquo;s roles and make sure they 100% understand what they need to do. Unfortunately, we live in a time and place where procrastination is one of the greatest issues with ourselves. As a leader, you must not succumb to this temptation and you must not let your fellow group members fall victim to &ldquo;last-minute moments&rdquo; either. <strong>Set deadlines and emphasize them.</strong> Don&rsquo;t use the &ldquo;absolute last-day deadline&rdquo; of the entire project. Instead, assign custom deadlines to the components of your projects that you are handing out to creatures of justification. And emphasize them too. Make sure that they understand that you are serious about these deadlines <s>and know that you will eliminate them from your existence otherwise</s>.</p>
<p>Another hard part of being a leader is dealing with the times when things don&rsquo;t go your way. Either you&rsquo;ve already planned for them beforehand (with backup plans) or you are forced to come up with an idea on the spot to solve this problem. Good leaders are solution-finders. They seek solutions instead of hiding from problems.</p>
<h2>Dealing with Irresponsible Group Members</h2>
<p>Unfortunately, we&rsquo;re not robots. There will be times when <s>you</s> us measly humans will mess up and not finish their part to your satisfaction. Truthfully, the worst thing you could do in such a situation is to criticize. It doesn&rsquo;t solve the problem, rather, it causes more tension and more resentment from your group members which will end up resulting in less motivation for them to do their future tasks well. The first thing to analyze in such a situation is whether they deliberately decided not to do their part. In that case, you&rsquo;ve got a much bigger problem (and will probably need to discuss it with the teacher). Otherwise, there are two main scenarios: the group member didn&rsquo;t have enough time to finish their part well, or procrastination got the better of them. If they didn&rsquo;t have enough time either from exceptions or an underestimation of the effort required for their part, schedule arrangements to help them or to split their job between other members of the group. Time is a constant and you shouldn&rsquo;t blame a group member for not being able to change it. On the other hand, procrastination and poor time management skills are another story. If the group member didn&rsquo;t finish their part because they decided to play video games instead of working on the project, you need to deal with that in another way. Again, criticizing and scolding won&rsquo;t help. Rather, sincerely trying to make them more motivated to complete their part (read the section &ldquo;Creating Motivation&rdquo;) will raise the chances of them putting aside their video games and putting genuine effort in making sure their part is complete.</p>
<p>Unfortunately, group members can also end up not having a part complete by the final deadline, which in this case matters become a lot more complicated. If this part was an important part that the project cannot function without, you should try not to regret giving this part to this group member (at least, when faced with the problem) and finding a solution is really dependent on the kind of project you&rsquo;re working on. A scary situation I can picture is a member failing to memorize their lines for a play. In this event, you should either try improvising or even say the other person&rsquo;s line yourself in some subtle manner: &ldquo;Sorry, what did you say? Oh, that <their line>? Well, <my line>&ldquo;. In the end, it&rsquo;s really up to you to make sure that your group is prepared and creating early deadlines is one extremely important (and simple) way of making sure you don&rsquo;t end up in these situations.</p>

<h2>Resolving a Disagreement</h2>
<p>Humans are made with their own opinions and judgments on what they believe to be the right idea. It is inevitable that people will disagree with you, perhaps even on a group project where you believe your idea is superior. The issue is, you can&rsquo;t just ignore others&rsquo; opinions, or they&rsquo;ll start ignoring yours. In other words, if you don&rsquo;t take a group member&rsquo;s opinion into account, they won&rsquo;t have the motivation to put effort into fulfilling your opinion on how the project should be executed.</p>
<p>Usually, opinions are backed up with a reason. When there&rsquo;s a disagreement about how one part of the group project should go, your very first step as a leader should be to listen and try to understand why they think their idea should be considered. You need to try your best to understand why they want to go through with their idea, even if it doesn&rsquo;t make sudden sense to you. You usually have two options to take: accept the idea into your plans in some way (which is often the better method), or to try to convince the person why the idea wouldn&rsquo;t really work out. As I&rsquo;ve said before, people love feeling important. If you incorporate at least some part of their idea in your project, they will feel that they&rsquo;re an important part of the project and will feel like they&rsquo;ve contributed. However, if you enter the rare case where this idea is so abnormal that you can&rsquo;t seem to find a way in combining it into the project without making it objectively worse, you need to try to persuade the group member why it wouldn&rsquo;t be a good idea. Your number one focus should be making sure that this project remains a <em>group</em> project and not a mini-dictatorship. You want to make sure you&rsquo;re listening to everybody&rsquo;s ideas, no matter how terrible they are. As a leader, you need to resolve disagreements among the group as peacefully as possible, for wars inside a nation are just as devastating from wars from outside.</p>
<p>Disagreement can come into play in many ways. Perhaps the most common one is during the formulation of a fundamental part of the group project, whether that would be a major choice (e.g. the research topic the group wishes to research) or a tough decision (e.g. the project&rsquo;s presentation date). Usually, you want to let everybody conjure up an opinion backed with reasons for their choice and try to think of as many problems with the choice. If these problems cannot be easily overcome, you should try thinking of different choices or approaches to these problems.</p>
<p>There are also minor quarrels such as who does which part of the project. The issue is, these minor quarrels oftentimes turn into big problems when handled incorrectly (e.g. an unmotivated member with a fundamental role in the project). It&rsquo;s very important to not criticize your members for arguing, no matter how stupid and ridiculous the argument may be.</p>

<h1>Dealing with a Leader</h1>
<p>You&rsquo;re probably not the only person who&rsquo;s looking for a good grade on a group assignment. You&rsquo;re probably going to be in a group with another person who wants to act as a leader. Usually, you would let them become a leader or agree to work together. A leader is the main conjurer of ideas and the main glue of the group. With this comes a potential issue, what if the leader is not a good leader?</p>
<p>Keeping rule #1 in mind, you never want to undermine somebody&rsquo;s efforts. It&rsquo;s likely that they aren&rsquo;t being a bad leader on purpose. Usually, you would want to help them and not watch them suffer trying to be a good leader. However, there will be times when they don&rsquo;t want your help and refuse to accept it. You will only create trouble by amassing a rebellion in your own group. Then, you may ask, how would you deal with a leader whose decisions are evidently poor and will only lead to a downright disaster of the final project?</p>
<p>Firstly, you want to understand why they believe their idea is worth following. If they ignore you, the only real solution is either trying your best to get your message across or if that doesn&rsquo;t work, consulting the person who assigned the project would be the next best option. Ignoring them back would only lead to a rebellion. Assuming they don&rsquo;t ignore you, you should try creating a chart that lists the benefits of their idea and the consequences this idea could entail. This will open their eyes to potential problems which could change their opinion and you will hear about potential solutions which could change your opinion.</p>
<p>The least productive thing you could do is tell somebody that their idea is terrible and then not provide a solution yourself. If you genuinely believe somebody&rsquo;s idea is terrible, the first step is asking how you can improve it instead of reinstating an idea of your own. As a group, you want to remind everybody of their common goal, to get the most out of this project as possible. If you can show everybody that an idea of yours can help everybody reach this common goal with negligible sacrifices, then you are much more likely to get them to agree or becoming willing to accepting your idea.</p>
<p>In the end, you should really try to help your leader as much as possible. If they become pressured from believing they aren&rsquo;t doing a good job, they&rsquo;re likely to become stressed and end up unmotivated in creating a great project. Cooperation is key, and making sure that the group continues to upload the main values of the project remains of large importance. If the leader forgets about something, kindly remind them about it without asserting that you would be a better leader. When they mess up, help them resolve it instead of laughing and pointing fingers. If they do something questionable, try your best to understand the reasoning and give ideas on improvement instead of downright deprecating their idea. Your job as a member isn&rsquo;t to rebel, it&rsquo;s to help revolutionize.</p>

<h1>Conclusion</h1>
<p>You&rsquo;ve reached the end of an enormous culmination of ideas on how to ameliorate the experience and results of your next group project. You&rsquo;re probably not going to able to apply everything single idea that I&rsquo;ve listed. However, if there&rsquo;s one thing to take away from this article, it&rsquo;s to give your members motivation and make them want to do the project well. The differentiating factor between a solo project and a group project is that not everybody wants to tend to your wants or opinions. It&rsquo;s your job to either change them or to make them worth considering. By ignoring ideas and criticizing failures, you&rsquo;re bound to lead your group project down a path of fragility and superficiality. A group project is also not just about you. You want to make it about being a group. You want to focus on the main point of its existence: to work as a group.</p>
<p>Remember that, and you&rsquo;ll be ready for every group project headed your way...both in school and in life.</p>
