<p><em>&ldquo;Start small and start immediately.&rdquo; - </em>Cal Newport, How to Win at College: Surprising Secrets for Success from the Country&rsquo;s Top Students</p>
<h4><strong>Project</strong> Definition</h4>
<p><b>Project:</b> a specific plan or design, a planned undertaking.</p>
<p>When I hear the term project, there are three things that come to mind. Individual projects, group projects, and self-projects. (I was originally planning on talking about all three of these in this article, but the length of just talking about the individual project forced me to keep these three project topics separate). In this article, I will be expanding on the individual and external project. These projects involve an external source of origin, as in, the project was given for you to do from someone other than yourself and said the project was explicitly assigned for yourself.</p>
<h4>Project Motives</h4>
<p>I assume that we all have a motive for completing a project that we get assigned, whether that would be receiving a good grade in return, a duty that comes with a future reward, and so on. It&rsquo;s also worth noting that sometimes a good grade isn&rsquo;t the best motive, and sometimes projects have motives that aren&rsquo;t necessarily what the project was originally for. For example, I received a project to write and present a speech, and I chose the topic of Habitica because it was something that I actively wanted to share with the world and to inform others about its potential. These motives can give you extra motivation to put greater effort into the project, and can still retain a side effect of maintaining or even strengthening getting that good grade/reward in the end. It&rsquo;s a mistake to undermine the importance of motives, as having one can dramatically increase your attitude, which in turn, produces deeper care and quality for the outcome of your work.</p>
<h4>Project Execution</h4>
<p>Unfortunately, only having a motive isn&rsquo;t enough. You can be fully determined and motivated to finish a project, but the execution of your project can be a big factor in the efficiency of execution during the process and the quality of your work in the end. As such, execution is one of the biggest factors that determine whether a project will go well...or not. If we glance back to the definition of this very topic, we find that the definition itself points us in the direction of making a specific plan, and calls a project &ldquo;a <em>planned</em> undertaking&rdquo;.</p>
<h4>Project Planning</h4>
<p>What exactly does it mean to plan? There are many answers to this question, and some may be more effective for some people while others are more effective for others. As such, to answer the question, it&rsquo;s important to reflect on why planning is important and to uncover the reason why it&rsquo;s crucial to plan in the first place. According to Merriam-Webster, one of the definitions of <strong>&lsquo;plan&rsquo;</strong> is <em>&ldquo;a method for achieving an end.&rdquo;</em> By substituting our topic into this definition, we get <em>&ldquo;a procedure or process for finishing our project.&rdquo;</em> In other words, a plan details the tasks we need to do such that the course of achieving the end goal of the project flows smoothly, and minimal time is wasted on the time-sucking question of <strong>&ldquo;what do I do next?&rdquo;</strong><p>
<h5>Scheduled Plans</h5>
<p>I rarely applied/took seriously my own deadlines for steps in the plan to a project, and there were a lot of times where I regretted this. Once you&rsquo;ve got the framework of your plan laid out, you optimally want to place a due date on everything, so that you don&rsquo;t end up producing sloppy work when you run out of time to do that part well. However, if you&rsquo;re like me and you&rsquo;re terrible at sticking to schedules, accountability tools (e.g. Beeminder) come in handy, because procrastination is a major killer of good projects. It&rsquo;s also important to mention that relative times can be more useful in some cases, especially when there is a dependency in the plan - when one step of the plan relies on another. It&rsquo;s also important to remember that these scheduled dates/times aren&rsquo;t just for making yourself more confident that you&rsquo;re going to complete your project, but you need to act upon them...right? Good time management skills and strong self-control are two major factors that come into play. You should optimally work on your project/step every day before its due date to make sure that you don&rsquo;t end up in the rabbit hole of &ldquo;I don&rsquo;t feel like doing it,&rdquo; and inevitably never wanting to start (see the paragraph &ldquo;When should I start/end?&rdquo;)</p>
<h5>Backup Plans</h5>
<p>There are two types of backup plans: the file backup, and the failure backup. The file backup is just like how files are backed up, an alternative copy (or at least a copy almost original to the original), and this plan is used for times where you can&rsquo;t get something working before the due date. An example of a file backup plan would be backing up your website that you chose to make for a presentation into an HTML file in a USB in the case that your website hosting service fails you on the day of presentation. The failure backup plan is for when a process that you originally planned to do failed, and you needed to find an alternative. There could be many reasons why a step could fail, but perhaps the most common is when exceptions eat up your time and end up pushing you way too far past the deadline for your step. If another step is dependent on the step you can&rsquo;t do, and these steps create a big part of your project, that can be a problem that can lead you to panic. A failure backup plan can come in different forms. One failure backup plan would contain an idea that the next step can still depend on, but the current step would take less time to do. However, a weak foundation can be a problem in this case. If you&rsquo;re not in the middle of a dependency, then finding a different base/path could be another failure backup plan, where you implement a different idea to replace your previous idea. For example, if you originally planned to create a video for your project, but deadlines were too strict to allow you to finish the video, you could try making shrinking it into audio, or make it a slideshow with audio. This would take less time, but depending on your situation, might be able to replace the video aspect while still supporting anything that builds on top of it (e.g. showing it in your presentation). Backup plans are only a slice of the cake of planning, and while they are still very useful, there&rsquo;s another slice that is perhaps more applicable and reaps greater rewards during the process of execution: optimization.</p>
<h5>Optimizing Plans</h5>
<p>Making plans go as gracefully as possible is a major time-saver. Optimization doesn&rsquo;t just mean making as little mistakes as possible, but it can involve always having something to work on, recuperating from mistakes (e.g. backup plans), and progressing forward as much as possible. You optimally want your process to be a one-way trip to the finish line. It&rsquo;s better to lengthen the path with a greater reward or to shorten the path with a higher effort-to-reward ration than to go back on the same path or lowering the reward/motive to the end. It&rsquo;s also better to walk on a bumpy road than to try and drive over it. Likewise, it&rsquo;s better to have new ideas that require more effort but give a greater value of the outcome, to give up (unimplemented) ideas that shorten the time and effort needed but still retain a high effort-to-reward ratio and to work slowly but steadily to your goal. Compare this with the opposite, where you move back on your path by giving up an idea you already implemented, giving up ideas/effort because they didn&rsquo;t work out, or building up your project on a rough and bumpy foundation for the sake of time. There are also other ways to optimize your execution stage, such as always being able to move forward. Perhaps this has a greater application to group projects (more on that later), but with individual projects, it still remains an idea. If you try to keep your planned steps independent of one another (when possible), such that when one step doesn&rsquo;t work out or can&rsquo;t be done at the moment, it won&rsquo;t affect the results of the other processes and in turn, you don&rsquo;t get stuck on fixing that one step that causes the other steps to become unreachable. An example of such an &lsquo;obstacle step&rsquo; would be when you need to research a topic before starting the write-up. By optimizing this step (e.g. printing out some sources), you are able to work on it when you wouldn&rsquo;t have been able to without the optimization, such as when you lack access to a device that can access the internet (which is pretty rare, but I digress). By making your steps as independent as possible, you are able to always progress forward on your project, and will always be a step closer to reaching the end goal and the rewards that come with it.</p>
<h5>Breaking a Project into Parts</h5>
<p>Take a look at these two plans:</p>
<p><strong>Plan 1:</strong> Brainstorm. Write a rough draft for the speech. Correct mistakes and make it a good draft. Memorize good draft. Add actions. Practice.</p>
<p><strong>Plan 2:</strong> Brainstorm a good topic, 3 points for thesis, and find examples that support these 3 points. Write a rough draft: Introductory paragraph should include a statistic (related to the topic), an overview, and a thesis. Paragraphs 2 to 4 should include the main point of the paragraph, 3 supporting points/examples. The conclusion paragraph should provide a summary of what I talked about, and end with an inspiring quote to end. Ask some friends for their opinion about the speech, and correct any awkward sounding phrases by reading it out loud. Add some potential hand movements to further enforce the point, and practice speaking with an expressive voice. Record myself practicing to find parts that sound awkward and make changes to speech as needed.</p>
<p>There&rsquo;s a great difference between these two plans. I&rsquo;m sure that there are people that think plan 2 is overkill, but in reality, when these two people tackle their same speech project, the plan 2 person&rsquo;s execution will flow much more smoothly. It&rsquo;s worth noting that a plan doesn&rsquo;t necessarily need to be written down because the purpose of the plan is to know what you&rsquo;re going to do next. Plan 1 can be good if that person knows why he&rsquo;s brainstorming, and has a plan like a plan 2 in his head, easily accessible when he needs it. However, it&rsquo;s not enough to create a plan like a plan 1 and think that you&rsquo;re good because you wrote a plan. If we follow through with the thought process of plan 1&rsquo;s writer, we will most likely find that his brainstorm either takes longer or is less of value than the brainstorm of plan 2, his points are probably more improvised when he writes his rough draft, which will lead to poor order, poor examples, and lead to a lot of effort and time needed in improving the rough draft. Plan 1 has a higher risk of wasting more time thinking about what to put on the speech, compared to plan 2 who knows their overall framework, and can substitute parts in order to complete the others (e.g. can put a template like [statistic goes here] and continue on with their intro paragraph whereas plan 2 has no idea what he&rsquo;s going to put on the intro paragraph and has a great potential to waste time thinking and to waste time constantly revising a poorly thought out intro sentence). By creating the framework of the project with a well laid out plan, you can become more efficient and produce higher quality work in the long run.
<h4>Project Resources</h4>
<p>After you&rsquo;ve made a plan, you can save time during the execution of the plan by making sure that you have all the resources you need for your plan (materials, tools, help, etc.). Materials include the parts that physically make up a part of your project, such as popsicle sticks, pipe cleaners, etc. For me, I have a material bin that I can rummage through to find any potential materials that I could use for my project so that I don&rsquo;t need to waste money (and often spend way too much) buying new ones when old ones would&rsquo;ve sufficed. With a few exceptions, projects shouldn&rsquo;t take too much out of your budget, and you (hopefully) won&rsquo;t take too long to buy all the materials you need. However, making sure that your creative part of yourself doesn&rsquo;t explode your wallet is also important because I still remember two projects I did that turned out to be quite interesting complements...</p>
<p><strong>Project 1 - History Fair: </strong>This project was actually a group project, but that&rsquo;s not the focus of the purpose of sharing this experience. My group and I put so much effort into this, and the effort was spread across multiple ideas that we implemented. We made a small trivia crack-like game, a complete dump of information in French and in English (9 pages long!), two small books, a 3D model and a short video (of which the latter two ideas turned out to be the most popular). The thing is, the project with all these amazing ideas only turned out to cost less than $30 (but way too much of our time). In the end, we won the most votes and won a History Fair certificate for this masterpiece.</p>
<p><strong>Project 2 - Science Fair: </strong>This project was assigned a year later (and actually replaced the history fair). This time, I worked by myself, and the topic I chose was making a hydraulic press. I wanted to take it above and beyond by making a large version; a version that didn&rsquo;t use the syringe-like pumps and instead used a homemade pump to push the water. The pump I built was based on the tutorial of Grant Thompson, and there were many, many things that went wrong in this project, one of which is the budget issue. This project...ended costing me over $200. I failed to research and plan the price of everything and bought everything as I went through the project...which is contrary to what I&rsquo;m advising (which you can see...didn&rsquo;t go very well). This pump ended up leaking because of compatibility issues, and I couldn&rsquo;t fill it with water at school to show what I made. Instead, I just pumped air (which definitely isn&rsquo;t as impressive), and now this pump sits in my garage...collecting dust.</p>
<p>One of these projects turned out much better than the other. Apart from just terrible execution, project 2 costed way more than project 1, and yet it didn&rsquo;t turn out as well and ended up being a terrible waste of money. Project 1, however, was way cheaper but turned out to pack way more value, and that goes to show that money does not necessarily mean a good project and that finding/using cheap resources in a smart way can end up giving a lot more value than using expensive resources.</p>
<h4>Project End Goals</h4>
<p>To be able to make a plan to reach our goal, we need to define our end goal, and to picture what our final finished project would look like. Obviously, the end goal of a project is going to be different for each project. However, the common end goals of each (I assume) are to get it complete, get it well done, and to collect the fruits of your harvest. The end goal of completion is important because unfinished projects don&rsquo;t often reap good rewards. As such, it&rsquo;s very important to consider the deadline of the project when picturing what you qualify as well done and to make sure that your inner perfectionist doesn&rsquo;t end up causing a far-from-perfect unfinished project. Let your logical and reasoning part of yourself take control of this part by making sure your end goal for your project is feasible to attain. However, fully relying on the safety and staying on the safe side of the line isn&rsquo;t going to get your project the attention you optimally want. By only fulfilling the minimum requirements, your project will end up just like everyone else&rsquo;s, and for most cases, that&rsquo;s not what you want. Getting a project well done means creating something that you&rsquo;re proud of, and knowing that you went above and beyond with your effort. Note that the term done is preceded by the term &lsquo;well&rsquo; for a reason, for it&rsquo;s not just important to get it done, but to get it <em>well</em> done so that you can reap the full rewards of your efforts. Tying this into the last common end goal of all projects, you want to get as much out of your efforts as possible. As such, the two ways to maximize this ratio are either putting less effort for the same amount of work or to put the same amount of effort for a greater amount of work. That&rsquo;s why it&rsquo;s important to be efficient so that you can make sure that your effort to value tradeoff is well worth your limited time and your limited effort.</p>
<h4>Project Efficiency</h4>
<p>Two main things are put into the execution of a project: time and effort. I assume that we all wish to complete projects as soon as possible, without sacrificing on the amount of work produced at the end of the process. Efficiency is the key to this goal. There are loads of ways to be efficient in general, and many of them apply to projects as well. As such, I feel that it&rsquo;s best to put the ways that can be directly applied to projects. One way is to make sure that you build your project from the bottom up. There were many times where I built something relating to final touches on a project...whose foundation didn&rsquo;t exist. Inevitably, the course of the project changed during its execution and time was wasted on making this final touch that was never used. You shouldn&rsquo;t build the roof before you build the walls of the house. Likewise, you shouldn&rsquo;t build a part of the project needed far off into the future of your project. Another way to become more efficient for projects is to keep a log of what you&rsquo;ve done and what you need to do. By doing this, you can see what you&rsquo;ve built, why you built it, and what to build next. Doing this can keep track of the path your project is taking and helps make sure that you don&rsquo;t waste time trying to think of what to build next. This makes it harder for your project to wander off the track of your plan, which often wastes time and effort. I&rsquo;ve experienced many times where I would go directly into a project, only to later erase all my progress and restart because I was making so many mistakes that the project took too much time and effort to fix and maintain. There were other times where I would create a master plan, and then find out that the deadline was quickly approaching and to find out that sticking to my plan was going to be impossible.</p>
<h4>When to start/end?</h4>
<p>You optimally want to completely finish (or as my friend puts it, &lsquo;dunk&rsquo;) the project before the deadline, and it&rsquo;s best to leave a few days after completion to review and add the finishing touches. However, it&rsquo;s important to not spend too long planning, or you&rsquo;re going to end up falling down the rabbit hole of procrastination. That&rsquo;s where the significance of the introduction quote comes from, for it&rsquo;s about how you need to start immediately and start planning, as well as doing what you planned, as soon as possible. Even if you&rsquo;re only doing a bit every day, as long as you&rsquo;re somehow involved with the project, you&rsquo;ll avoid the loophole of starting later.</p>
<h4>Common Project Mistakes</h4>
<p>I&rsquo;ve already written a lot of ideas in this article that you can implement to make your projects go smoother, as well as the risks that can potentially come up if you don&rsquo;t follow through with these ideas. Think of this paragraph as a summary of these ideas:</p>
<ul>
    <li><strong>Not Planning:</strong> Creates the potential problem of wandering off track, creating sloppy work, as well as leaving the problem of wasted time when thinking of what to do next.</li>
    <li><strong>Weak/Bad Planning:</strong> If you create bad plans, you end up with wasting time on making the plan, and then not really following through with the plan because of how lacking in detail it is, and then ending have restarting because of second thoughts, indecisiveness and doubt. Also, plans without a strict schedule/deadlines can come back to bite you if you run out of time and are forced to scrap ideas from the plan that were a big part of your project.</li>
    <li><strong>Dependant Planning:</strong> If you create steps that depend on another to be completed before they can be tackled, you will get stuck on this one step that will eat up the limited time you have for your project. By making these steps independent of each other, you allow yourself to always have something to do and not get stuck on only one step (and you&rsquo;re probably familiar with discovering a solution when you aren&rsquo;t actively working on the problem...frustrating).</li>
    <li><strong>Too Much Planning:</strong> If you spend too much time planning/fantasizing and never really start your project, time becomes a major issue and your plan is going to end up obsolete because of how much time you spent creating it. It&rsquo;s also important to not make your plan too specific because it&rsquo;s likely that your opinions/decisions will sway and time will get wasted trying to think up of an extremely precise algorithm you want to follow.</li>
    <li><strong>Lack of Backup Plan:</strong> If your original idea/step doesn&rsquo;t work out, and then you don&rsquo;t know what to do, time is wasted thinking, experimenting and panicking about what to do next.</li>
    <li><strong>Poor Execution:</strong> If you don&rsquo;t stick to the deadlines/steps of your plan or start working on your project, you&rsquo;re creating a rabbit hole of failure for yourself to fall into.</li>
    <li><strong>Wasted Resources:</strong> Ties back in with planning, make sure you list the things you will need for your project so that you don&rsquo;t end up buying them as you go and wasting time and money (as such, it&rsquo;s important to try and stick to your plan as much as possible. As well, you will have to probably buy something you overlooked, but don&rsquo;t rely on this too often as resources aren&rsquo;t always available 24/7).</li>
    <li><strong>Dependance on Resources:</strong> Try not to depend on new resources and try to make the best of your situation with the ones you have. This allows you to save time shopping, and also shows off your creativity and gets you bonus marks ;) (and also saves your wallet, but who cares about that?)</li>
    <li><strong>Lack of Motive:</strong> Creates friction between getting the project done well and putting in effort. A motive helps give you more incentive to work and do well on your project.</li>
    <li><strong>Poor Motive: </strong>Having a potentially weak motive, such as a good grade when you don&rsquo;t really care about grades, can cause your project to become sloppily done. Try finding a motive besides what the project is guaranteed to produce (e.g. informing the audience during a presentation project about something that you are passionate about, as well as getting that good grade...almost as a side-effect).</li>
    <li><strong>See Below!</strong></li>
</ul>
<h4>Start!</h4>
<p>Once we&rsquo;ve got an end goal and a process in mind, the next step is to start. Don&rsquo;t try perfecting your process and putting in every single detail, because chances are that your process isn&rsquo;t going to go exactly as you pictured. You might not have enough time to attempt a part of your process, or maybe another step didn&rsquo;t quite work out (backup plan!), so it&rsquo;s best to get into it and make (preferably small) changes as you go.</p>
<p>So, go on, and get started ;)</p>
