<p><strong>Note:</strong> For this article, I may sometimes refer to <strong>j</strong>ust <strong>i</strong>n <strong>t</strong>ime <strong>l</strong>earning as JITL.</p>

<h3>Definition</h3>
<p>
<strong>(Dictionary.com) Learning:</strong> the act or process of acquiring knowledge or skill.<br/>
<strong>(Cambridge Dictionary) Just-in-time:</strong> A system of manufacturing (= producing goods) based on preventing waste by producing only the amount of goods needed at a particular time, and not paying to produce and store more goods than are needed.<br/>
For this article, the definition of just-in-time will be applied to learning instead of only manufacturing, leading us to a broader definition of just-in-time below:<br/>
<strong>(Broader Definition) Just-in-time:</strong> A system based on preventing excess by producing only the needed quantity at a particular time, and not investing in storing more than needed.<br/>
Combining these two definitions for &lsquo;Just-in-time learning,&rsquo; we get:<br/>
<strong>Just-in-time learning:</strong> A system of learning based on acquiring only the necessary knowledge or skill at a particular time, and not acquiring more than needed.<br/>
<p>JITL involves putting yourself in a situation designed to force you to actively interact with what you want to learn. By forcing you to find solutions to problems you encounter, JITL provides a more active way of learning that helps you better retain your knowledge and grants you a deeper depth of such knowledge.</p>
<p>In simplest terms, JITL can be summed up with comparing it to traditional teaching methods. The latter is based on teaching the material before exposing one to it, where JITL is based on exposing one to the material before its teaching. An example that may help illustrate this comparison would be with programming. The traditional teaching method would focus on teaching the what the students need for an assignment before giving them the assignment.  The JITL approach would give the students an assignment before they learn (or after they learn the <em>very</em> basics needed for the assignment), and the students would be expected to find the answers and come up with solutions as they go.</p>
</p>

<h3>My Opinion on JITL</h3>
<p>I&rsquo;ve used JITL in a myriad of situations in my own learning. I believe that it is a powerful way to learn a new part of a grander subject. There have been many times where JITL&rsquo;s central goal (exposing one to the material) as proved more efficient and beneficial than the material&rsquo;s learning before its application. When practiced correctly, JITL provides a startling effective way to gather a basic knowledge or understanding of a concept that allows for an easier digestion of a deeper knowledge of the material.</p>

<h4>Experiences with JITL</h4>
<p>JITL has proven most useful to me when I wanted to build something that required the knowledge of a subject that I wasn&rsquo;t familiar with. In particular, you may have heard about my typing game that I made with a friend. Building that required the knowledge of socket.io, which I had absolutely no idea how to work with at the time. If I chose not to use JITL learning for this, I would&rsquo;ve spend a long time studying the documentation, reviewing all the API functions, etc. However, with JITL and by just jumping in and creating it, I was able to learn a lot in the short time period that I used. Whenever I didn&rsquo;t know how to do something, that&rsquo;s when I would look at the documentation or even just search the answer up online, and I believe that by using JITL to learn, I was able to accomplish and create something much more easily and efficiently compared to if I were studying all beforehand and only starting when I felt comfortable with it (which would&rsquo;ve taken much longer).</p>

<h3>When to use JITL</h3>
<p>JITL is useful for scenarios where the topic you wish to learn is something that you want to apply quickly. If you&rsquo;re in a situation where you don&rsquo;t know how to move forward, JITL allows you to continue applying what you already know and exposes you to what you don&rsquo;t know you don&rsquo;t know. That being said, you can think of JITL vs. learing before application as two manufacturing companies (which is what just-in-time was originally used for). JITL would provide and create the product whenever it was needed, whereas learning before application would have the company produce a ton of products before releasing it to the public. As you can see, JITL can sometimes end up more efficient and creates less waste, as well has having the bonus of starting earlier and learning quicker at first, whereas learning before application is hindered by the process of creating everything and can also end up not selling all their products, in which case waste is produced and ratio between effort and outcome is decreased.</p>

<h3>When to not use JITL</h3>
<p>There are many times JITL can end up less efficient than other learning methods. One of such cases is how JITL can really only be used in scenarios where the topic can be applied (as it requires actually applying what you aim to learn), and as such has a time and place restraint that other methods don&rsquo;t necessarily have. An example would be a topic of JITL that requires a computer (e.g. learning to make music), and the restraint in this case would be locations where using a computer is impractical. Another time where JITL wouldn&rsquo;t be the best strategy to use is when you wish to acquire a deep understanding of a subject in which topics that come up can be uncommon to encounter with JITL. A deep understanding of a subject will be necessary in many parts of its application, such as writing an exam that tests what you know instead of how you learn. In these cases, a review of the a greater range of a topic (especially reviewing the uncommon parts of the topic) is more practical than what JITL provides. In many cases, especially in competitive scenarios, JITL only exposes the more common outcomes and demands of a subject, where the winning hand would rely on knowledge of the more unusual and uncommon topics of which less people are likely to possess a deep understanding. In these cases, methods such as studying from a textbook or enrolling in a course may be more beneficial than the JITL strategy.</p>

<h3>JITL and Active Learning</h3>
<p>While writing this article, there were a lot of ideas that came to mind, but were all more related to the topic of active learning rather than JITL. The relationship between these two topics is that JITL is a form of active learning, where active learning is an umbrella term in which a strategy that promotes active learning would include JITL. As such, there were a lot of ideas that were left out because they would better apply to the topic of active learning more than JITL itself. I don&rsquo;t plan on making a whole article about active learning soon (because it would be really, really large), but I can provide some strategies in which active learning is practiced (such as this very article).</p>

<h3>How to apply JITL</h3>
<p><em>Start!</em> Expose yourself to the things that you don&rsquo;t know you don&rsquo;t know, and learn as you go. Take what you want to learn, find out why you want to learn it, and start doing just that! Start doing what you&rsquo;re learning for! Of course, this isn&rsquo;t always applicable to every topic, and some may benefit more from JITL than others. However, even if you didn&rsquo;t get much knowledge of the topic itself from JITL, you may end up with a lot of questions about the topic that you&rsquo;ve been exposed to with JITL. Keep a list of those, and return to it as you continue learning the topic. JITL is a way to expose yourself to the amount of knowledge that is in something you want to learn...try not to get intimidated! Instead, look forward in optimism and keep your head up for more surprises to come!</p>
