<p><strong>SSS: </strong><strong>S</strong>uper <strong>S</strong>tudy <strong>S</strong>ession.</p>
<h3>SSS?</h3>
<p>The term SSS was created to describe a study session that was above (hence the term &lsquo;super&rsquo;) a typical study session. I chose the acronym SSS because I find it easy to remember and I also find aliterations fun. Besides that, I wanted to come up with an acronym in the first place to make it different from just a normal study session; I wanted it to be something special that would give me more motivation to go through with it.</p>
<h4>&lsquo;Super&rsquo;</h4>
<p>A regular study session is always better than none at all, but I feel that these study sessions can get dull, and they rack up a bad reputation for being mind-numbingly boring. As such, I wanted to make an extreme version of a study session, and give it a reputation for being extremely hard, which would give the motivation to finish it because of how difficult it is. The term super refers to how it isn&rsquo;t just your average study session, but rather something that is built to push you beyond your limits. We all get motivation from doing something that challenges us, and the SSS is one of those challenges. I wanted to make the SSS something that one would be proud of completing, and would be a learning opportunity that&rsquo;s greater than just a regular old study session.</p>
<h3>SSS Experiences</h3>
<p>My first SSS was the WBS, the <strong>W</strong>inter <strong>B</strong>reak <strong>S</strong>SS. This SSS was the most productive time I had ever had in my life; I had reached 168 hours of work in a bit over 2 weeks and studied for a minimum of 10 hours per day. I also learned a lot from this success, such as:
<ul>
<li><strong>Time Management:</strong> The first day of my Winter Break SSS, my thoughts for the day were very simple: &ldquo;There was a lot less time than I thought was available to me.&rdquo; Interestingly, on this day, I woke up at 6:30AM and slept at 8:45PM (back when I actually cared about my sleep...), and this meant that I had over 14 hours to get stuff done. However, interestingly enough, I had only gotten 10 hours and 40 minutes of work done that day. This meant that over 3 hours were wasted, which had surprised me at the time because I thought that I could be a completely efficient robot when it came to the SSS (I know better now).
<ul>
<li><strong>Focus:</strong> &ldquo;Today, I was pretty much forced to do something other than C++. I was so tired, that I even put ice cubes down my shirt to keep my awake, which helped a little. However, when I switched topics and introduced my mind to a new topic, I was able to stay awake and actually get stuff done. However, I do plan to continue to focus on my C++ textbook and only switch when I actually can&rsquo;t get anything done if I were to continue.&rdquo; During this SSS, I learned that having a sole focus for too long will get boring, and especially without enough sleep, this lack of energy will lead to friction in the efficiency of the learning process. However, it&rsquo;s also important to remember that a lot of subjects can also lead to a focus that&rsquo;s too wide, and this focus would cause you to end up not learning much at all (see [extract] below).</li>
<li><strong>Extremes:</strong> &ldquo;Just barely made it over 10 hours, I now know the worst this challenge has brought for me (as of now...).&rdquo; This is where you need to continue treading through the struggles of the SSS, and these are where the sacrifices are made. You need to make sure that you will be able to get through the challenges the SSS provides and not simply dismiss it, for doing that will inevitable end up causing the whole project to fall apart.</li>
<li><strong>Thy Fudge Ratio:</strong> Day 6 was the day I began to realize some side effects: &ldquo;I have zero time to do anything else that I would like to do, especially my other Pick 4 Goals. 10 hours should&rsquo;ve left me with 5 extra hours for other things, but that has been nearly impossible to do because of the extended length of my breaks. Today, I even planned to get everything done by 8 PM after accounting for a &lsquo;likely&rsquo; one hour of breaks, but it ended up being twice that much, and waking up at 9:00 did not help matters. Next time, I&rsquo;ll make sure to keep track of how long my breaks are, and I&rsquo;ll try to calculate my Fudge Ratio to get a better understanding of how much I overestimate things so I can take that into account in the future.&rdquo; I&rsquo;m interested as to my mentioning of the Fudge Ratio. If you&rsquo;re not familiar with this term, it&rsquo;s basically the ratio of how much time you think you can get something done and how much time it actually takes you to get it done. As an optimist, believing that I would waste zero time and achieve automation perhaps wasn&rsquo;t the best belief to rest upon...</li>
</ul>
</li>
<li><strong>Active Learning:</strong> On the second day, I also only had one thought: &ldquo;Honestly, time flew by really quickly today. I believe that it was because of a fun chapter that I was on, with active programming projects.&rdquo; Most of my time spent learning programming during the WBS was doing exercises (practice programming problems), and this is an example of active learning. Compare this to the book I want to learn right now, TC++PL 4th edition, completely filled with information but with very little relevant practice problems (which I don&rsquo;t blame them for, this book has a ton of useful information), makes it very hard to learn without getting bored because of how passive it is. This day showed me the importance of active learning, and why 10 hours isn&rsquo;t hard when you&rsquo;re actively involved in doing something rather than passively observing.</li>
<li><strong>Health Issues:</strong> Interestingly enough, I was only on the third day when my sleep schedule started to shift towards the negative side and when I became aware that this might not be too good for my health. &ldquo;[M]y eyes and brain are dead, at a total of nearly 12 hours of work...not very good for the days to come.&rdquo; As well: &ldquo;10 hours on a chair has started to become a problem. I have noticed consequences of not being active for 10 hours every day. &ldquo;</li>
<li><strong>Sleep:</strong> &ldquo;Sleep makes that much of a difference. Being able to sleep early to wake up early and get everything done before your eyes go dry is a great feeling.&rdquo;</li>
<li><strong>Justification:</strong> &ldquo;Wasted quite a bit of time conversing with friends, but I did use the time working to stay very productive, and had a lot of time to spare[.]&rdquo; Looking back on this, especally since my sleep schedule was already failing, conversing with friends wasn&rsquo;t the best idea, and it intrigues me how I was able to justify wasting time when I could&rsquo;ve been catching up on sleep. When your brain starts getting tired, it&rsquo;s very important to make sure that you catch yourself justifying poor decisions.</li>
<li><strong>Exceptions:</strong> Day 5 was the day I was subjected to the exceptions: &ldquo;Being forced to watch a movie isn&rsquo;t an excuse that you would hear every day[.]&rdquo; This threw off my sleep schedule even more, and I ended up going to sleep at 10PM that day...and really regretted my decision to not catch up on sleep when the opportunity arose.</li>
<li><strong>The Gradual Improvement:</strong> After this WBS ended, I looked back at my stats, and noticed that my productivity was gradually increasing as the days went on. When I started this, I was averaging about 80% efficiency and the days before its end, my efficiency was averaging over 90% and I had even achieved a perfect day (no distractions).</li>
<li><strong>The Perfect Day:</strong> &ldquo;Today was the optimal day. I worked with the only breaks being my meals. No distractions (during the work time, I admit I wasted an hour afterwards) whatsoever. Something I learned from this was actually not from the work session itself, but from the aftermath. A fixed schedule is something that&rsquo;s extremely needed for your day. When I finished my 10 hours, I had no idea what to do (and was too bored to do my homework), and ending up wasting an hour which could&rsquo;ve been used a lot more wisely (such as working on my schoolwork). This shows the importance of having a daily to-do list that won&rsquo;t run out (there will always be another task), so that your time is used to its maximum potential. I think that instead of working on my homework, once I finish eating dinner, I&rsquo;m going to sleep so that I could wake up really early and finish early so I can allocate time to finish my homework...which is quickly rising to the top of my priority list and risking a stressful & sleepless night on the last day... Update: I did not sleep, instead, I thought it would be a better use of my time to get videos edited, erase my RocketBook (which takes quite a long time), and to schedule my days after the Winter Break.&rdquo;</li>
<li><strong>Aftermath:</strong> I had a Pick 4 Challenge going on before the WBS, and in total this would take around an hour and a half of my time. However, due to the intense focus, I was unable to complete these Pick 4 goals during the WBS, and decided that I would continue them after. However, even though I had originally maintained them well, after the WBS was over, it was hard to get back into these 4 goals and I ended dropping them altogether later on. I was not aware that was going to be the case, and this outcome may just be a result a lack of self-control.</li>
<li></li>
</ul>
Sadly, I haven&rsquo;t been able to top that record ever since I did it on December 2019, during the two free weeks (no school) of Christmas Break. Interesting enough, I haven&rsquo;t been able to succeed on another SSS yet...</p>
<h4>Failed Attempts</h4>
<ul>
<li><strong>The LWSSS -</strong>Standing for <strong>L</strong>ong <strong>W</strong>eekend <strong>S</strong>SS, this was the next SSS I attempted after the WBS. Unfortunately, it was also the first taste of bitter failure in my mouth. I...never got around to doing this SSS. Looking back at my empty logs of this failed session, I remember that I had plans to work on my website during this period, but then decided to work on programming, and inevitably ended up treating it as a normal weekend because of a lack of motivation. Unlike the WBS, this one wasn&rsquo;t hyped up and I failed to build enough motive to tackle it, and ended up not taking it seriously.</li>
<li><strong>The PXS -</strong>Standing for <strong>P</strong>ost E<strong>x</strong>am <strong>S</strong>SS, this study session had around the same time frame/period as the LWSSS, but was scheduled to be done after exams were finished, which gave a week of free time. Interestingly enough, I actually started this SSS but gave up in the middle of it because of how inefficient it seemed to be. Luckily, I kept a log of my experiences and can review why this SSS was a failure:
<ul>
<li><strong>Sleep:</strong> This has been a deadly factor in pretty much all of my SSSs, and sadly sleeping late and right after screen time is still a poor habit that I can&rsquo;t seem to break. I started off the SSS with a poor amount of sleep, which is inevitably going to lead to an even more distrupted sleep schedule and further destroy my productivity. The lack of sleep had also caused me to fall asleep during work periods and also cause me to waste time because of my zombie reading the textbooks (see point on &lsquo;Active Learning&rsquo;).</li>
<li><strong>Lack of Preparation:</strong> I wasn&rsquo;t really committed to starting/finishing this SSS, and my mindset was more focused on just getting something done over the free time I had, rather than the proper mindset of getting as much done as possible. One of the clear lack of preparation mistakes I made was forgetting to activate my distracting website blocking software (Cold Turkey), which led me to inevitably fall into watching YouTube. One other interesting thing to note is that for my WBS, I had planned for it an hour in advance, whereas with this SSS, I had acknowledged doing it one day before I actually did...</li>
<li><strong>Passive Learning:</strong> There are two main types of learning, passive and active. Passive learning is what I did during this SSS: reading textbooks without taking notes. This led me to not build up a solid enough foundation for continuing on with the SSS, as well as the lack of interest causing me to swap between three textbooks often, which would force mut o do more work because I would have to break out my work mode every so often or else risk falling asleep and learning nothing...which looking back, I should&rsquo;ve probably taken a nap to boost my energy levels instead of dunking my head in cold water...</li>
<li><strong>Distractions:</strong> I probably should&rsquo;ve locked my phone in the closet or at least turn it off, because Gmail notifications would come through and I&rsquo;m pretty much obligated to check it. This led to a dent in my work/productive mode and would have me put more effort into rebuilding that state of mind. This led me to eventually lose motivation because of how slow I was progressing.</li>
<li><strong>Failed to keep Suggestions:</strong> Interesting enough, I already discovered the problem with passive learning on the second day of this SSS, but and I deliberately mentioned in my log that I should be taking notes and actively learning the material. However, </li>
<li><strong>Poor Resources:</strong> This one might be a small speck of the real problem, but during this SSS, one of the topics I wanted to learn was C#. However, the textbook I used was outdated, and this forced me to search for solutions on StackOverflow and whatnot, which inevitably led to me wasting time on the internet searching &ldquo;Should I really learn C#?&rdquo; As well, when I couldn&rsquo;t find how to get a solution, I was stuck on a main part of the book and couldn&rsquo;t really move forward. Also, just a side note, most of this C# book talked about material that I had already learned, which just goes to show that 1000+ pages doesn&rsquo;t necessarily give you 1000 &lsquo;units&rsquo; of knowledge. It was also really boring.</li>
<li><strong>Poor Time Management:</strong> One of the other things I had to do during this SSS was practice the piano. However, terrible time management skills and terrible self-control led to me pushing the time I would play further and further into the day until it became too late. I&rsquo;ve partly fixed the issue now, for I&rsquo;ve set up a Beeminder that will charge me $5 if I don&rsquo;t play two hours of piano (and I will admit I had to lie because of simply not enough time being available for the day). However, during this SSS, I had nothing like that, and the core problem of this specific case loops back to a lack of preparation.</li>
<li><strong>EXCEPTIONS:</strong> This term gives me nightmares, both in programming and in real life. During this SSS, I was invited to come to the Ontario Science Centre and apparently it was all already planned out (without my knowledge!), so I was pretty much cornered into going with my friend (none of this was his fault). The issue was, this event sapped so much of my energy that coming back and doing work was not an option. I actually tried filling a bucket with ice-cold water and dunking my head in it every so often, but this honestly didn&rsquo;t seem to help. I think I&rsquo;m going too extreme with working, and that one of my solutions could potentially be to just take a nap when I feel that my energy is low. This would allow me to better concentrate on the material instead of dozing off every 10 minutes and forgetting everything I just read.</li>
<li><strong>Extreme Expectations:</strong> I should&rsquo;ve adjusted my 100 hour goal a bit when I had to deal with the 5-hour exception at the Science Centre. I should&rsquo;ve have tried so hard to reach this extreme number, and it ended up causing me to fail because of how much it asked from me, and how little I was able to give back. Forcing myself to cut back from sleep when I needed a boatload of energy wasn&rsquo;t the most brilliant idea, and by only making my sleep situation worse, my productivity level was only going to deteoriate from then on.</li>
<li><strong>Poor Time Planning:</strong> Trying to cope with 8 hours of sleep and 10 hours of work is already bad enough, but ruining the sleep quality multiplies the issue. There were many opportunities to avoid screen time before sleep, but I failed to manage my time properly and ended up watching a screen for several hours before going to bed. This dealt quite a toll on my energy for the next day, and continuing this habit was something that would inevitably lead to the end of this SSS. Interestingly enough, this bad habit of screen time before bed is still something I struggle with today.</li>
<li><strong>Health:</strong> Staring at a screen for extend amounts time while deprived of sleep and energy is something that will come back to bite you in the long run. During this SSS, my eyes were extremely red and hurt, and this distracted my focus on learning quite a bit.</li>
<li><strong>Poor Choices:</strong> Several hours were wasted trying to install something that I could continue working without (more specfically, the newest C++ compiler). The root of this issue was really just me trying to avoid working, which isn&rsquo;t really in accordance with the whole idea of the SSS.</li>
<li><strong>A Broad Focus:</strong> With the WBS, I learned a ton because my focus was set on only one thing, and one specific thing: C++. During the LWSSS, I was trying to learn C++, C#, Ruby and Algorithms, and on the fourth day I even resorted to pulling out my math textbook. The root of this detriment is not so much wanting to learn more, but more about wanting to have more to do.</li>
<li><strong>Lack of Motivation:</strong> When I told myself to take notes to avoid passive learning, I really didn&rsquo;t put much effort into making sure that I would actually do them. I&rsquo;ve heard about people making their notes public to make them forced to take it, but I did no such thing, and as a result, I continued zombie scanning these textbooks and ended up gaining little knowledge at the end, which also meant that my foundation wasn&rsquo;t solid enough to continue on.
<p>I had a friend that tried to do his own SSS, and made it &lsquo;super&rsquo; by trying to stick to a minimal sleep schedule. He called this a NSS (<strong>N</strong>o <strong>S</strong>leep <strong>S</strong>SS). His original plan was &ldquo;to sleep later, and to wake up earlier.&rdquo; When he told me about this challenge, I was questioning if it was going to work out at all, because one of the important things I&rsquo;ve learned from my SSSs was that sleep is extremely important. As I thought, this SSS ended up being a disaster. His body&rsquo;s need for sleep was greater than his motive to get up early (which is what he struggled with, he could easily sleep late but struggled to get up early). When I asked why this was, he told me that his alarms couldn&rsquo;t wake him up (and if this was me, I&rsquo;m sure that my mind would ignore them too). However, another weak point in this SSS was his motive. He told me that his motive for this SSS was to get better than someone else. Originally, this seems like a good motive because it challenges you to improve yourself. However, he then proceeded to tell me that when the person you&rsquo;re competining with leaves a greater gap between their knowledge and yours, you start to lose motivation and negative thoughts of &ldquo;You won&rsquo;t be able to reach his level&rdquo; start flooding your head. I think that this situation is extremely interesting, because my friend was competing against was me, and when I found out, I was extremely shocked, because I feel the same towards others above my level. However, in my case, I don&rsquo;t try to compete with them, and focus on the mindset to know that I get smarter than my past self when I learn more, and focus on the glass half-full part of things. By comparing yourself to someone who&rsquo;s really above you, you start to forget your real motives and you also risk losing a lot of the true motives that you should always be following. It&rsquo;s important to not be blinded by others because walking down a path blind will eventually lead you back to where you started. Rather, by looking at the footsteps you leave, and focusing on passing your previous footprint will lead you to the other side; where you want to be from where you started.</p>
</li>
<li><strong>Timeboxing Failure:</strong> Partly within my control, and out of my control. The out of the control part of this was the events that occured that caused variable times and exceptions. What was in my control, however, was to react accordingly to adjusting my time and work to account of these times. I did not such thing, and I blamed it too much on what I had no control over rather than blaming it on my not taking proper control of what I had control over. These annoing variable times and poor handling of these nuisances got me frustrated and lowered my motivation to continue this SSS even more, which ultimately led me to give it all up.</li>
</ul>
</li>
</ul>
<p>This post is far from complete, and will be updated with my upcoming SSS experiences as I take upon them. I hope this article gave you some incentive, as well as tips, to help you with completing an SSS of your own.</p>
