<p><strong>School:</strong> an organization that provides instruction.</p>
<p>I catch myself ranting about school a lot. I'm also catching myself saying a lot about school that I don't feel 100% sure about. In this article, I'd like to point some of these things out and see if my discontent with school seems reasonable...</p>
<h1>My Definition</h1>
<p>First off...before I dive into pouring out my feelings, I'd like to define the term. In this article, I will be talking about the school which I am forced to go to for a bit more than 6 hours a day, 5 days a week (most of the time). Another type of school is the extracurricular kind for learning ahead or catching up. Those schools aren't mandatory (unless you're parents decide otherwise) and I've never really been to these institutions enough to have a solid opinion about them. As such, they won't be a focus in this article.</p>
<h1>My Opinion</h1>
<p>To be clear: I don't <strong>hate</strong> school. I simply rather prefer I didn't go there. My opinions are driven by my beliefs and my personal experiences.</p>
<h2>My Beliefs</h2>
<p>My stance on learning is vastly different from society's common ground: work to retire. In other words, schools seek to educate people enough so that they can get through the next 50 years of their lives and retire after fulfilling a dull, normal life. That's not what I believe in. You should learn to become useful to others, not just to yourself. By having this toxic mindset of learning for your own good, schools start to undermine the true value and worth of learning. They start to turn education into an institution that produces the <a href="https://people.wku.edu/charles.smith/MALVINA/mr094.htm"> little boxes who come out just the same.</a></p>
<p>You may be a bit confused if you associate school with learning. That's not wrong, but that's not fully correct either. Schools were made to get people educated. If being smart is defined as being educated more than average, they don't care about making people smart. They care about making people not below average and the people who want to be more than average are those they take down with them in this process. They don't provide an option to prove yourself worthy of learning more on your own if you have the potential. Rather, they assume that all teenagers are rebellious and don't like learning. They assume that we would give up learning if we were given the choice. As such, school is mandatory and wrongfully so.</p>
<h3>Clarification</h3>
<p>If you believe school shouldn't be mandatory because you should have the choice to choose to learn, I am completely against you in that regard. One of the main reasons for the big difference in many countries (first-world vs. third-world) is because many don't have access to education. If not being educated can cause a whole country to struggle, then it's extremely evident that people should not be given an option to not learn and not get educated. Education is a privilege, and I can't argue with that. I fully agree with the government making education mandatory. I fully disagree with the government making school mandatory. If you can show pure interest and potential in learning on your own, you should be able to pursue that interest without school keeping you from doing so.</p>
<h2>My Personal Experiences</h2>
<h3>My WBS19</h3>
<p>My WBS19 was a huge perspective-changing experience when it comes to viewing school. In 2 weeks, I was able to learn pretty much what school would take around a year to teach. For me, this shows that school is...inefficient. Even worse, it shows that school is actually slowing down progress because it shows you can learn more in 2 weeks on your own than you can in a whole semester. As such, by making school mandatory, you end up forcing students into inefficient institutions increasing intellectual insufficiencies. In other words, you are forcing capable students to learn slower...</p>
<p>I'm not in favour of expanding the length of weekends. Nor am I in favour of shortening the time we must go to school. I'm in favour of the option to go to school if one has proven themselves qualified enough to learn the topic by themselves. I'm also in favour of allowing students to choose what topics they're interested in and don't support forcing students to learn some topics that they don't plan on following in their future. If a student can learn more on their own, <strong>let them learn on their own!</strong> After all, schools aim to educate people, so do just that by allowing students to educate themselves if they have proven themselves capable!</p>
<p>The sad truth is, schools don't care if you want to learn faster. They tell you to learn on your own but then still repeat the same material without allowing exceptions for you to learn on your own when they're teaching. If you complain that you already know this, they really couldn't care less. Schools were made to make people more educated overall, but with this came the issue of making the more educated people...less educated. How? By taking away 6 hours of their day dedicated to trudging through topics that they already know. They force the majority to walk through the mud with them because they're afraid that giving people a choice to figure out a better way to get to the other side by themselves would end up in some people abusing that choice and not trying at all. In other words, they force everybody to learn at a slower pace because they're afraid that if they give the option to learn on your own that too many 'unqualified' people will use this choice and end up uneducated at the end. I'm fine with trying to educate the majority, don't get me wrong, but the fact that it's the law to get educated without there being some sort of test freely available to test for qualification for self-education is something that I am strongly against.</p>
<h1>What can we do?</h1>
<p>Obviously, you can't drop out of school until you become Grade 10 (at least where I live). You also probably don't want to upset your parents either, because schools have already wrongfully established themselves as the key to open the lock of the door of good futures. However, I'll also give you a key. This is also a key that can open this door. It's simply proving yourself. Prove that you have the potential to exceed what school provides for you. School isn't made to keep you uneducated, it just becomes that way for you when they follow their philosophy. You don't need to sacrifice your marks to fight back. Rather, when you find yourself in a situation where the topic being taught is of no use to you whatsoever, find mediums applicable to get productive. When I can't pull out my laptop and work on my website, I pull out my phone to study Anki. When I can't study Anki on my phone during class, I pull up a piece of paper and practice my Gregg Shorthand. When I can't use any material, I whisper ideas for articles into my voice recording wristwatch. If I get in trouble for doing any of these things, I will accept my punishment and I wouldn't be afraid of them "telling my parents" because I was learning at a time where I had the option to do nothing. I was taking education upon myself and being punished for that is something that I shouldn't be afraid of telling others.</p>
<p>Let me ask you this. If you were an employer, would you be more impressed in an average person who got the majority of their education in school, no matter how prestigious the school is, or someone who gathered the majority of their education from self-learning and have proved themselves as educated, if not more, than the person who received their education from school? Even if this person wasn't as educated as to the one coming from the formal institution, they have proved themselves capable of taking education upon themselves and have demonstrated that they can learn topics without the need of others teaching it to them. That is a skill that is extremely relevant in today's society and schools lack a course for just this; school doesn't teach people <em>how to learn on their own.</em>
<h1>Proving my Point</h1>
<h2>Increasing Class Sizes</h2>
<p>Because of our absolutely idiotic government, we now expect an increase in class sizes for the next school year to come. Not only is this further proving my point, but it also means that I have to deal with this nonsense. It also means that I have to waste more willpower in trying not to emerge in a full-out rant when the topic of efficiency and school clash together.</p>
<p>"By putting more students into one class, we have more students learning at the same time and therefore coming out more educated while keeping budgets low." No. That's not true. Rather, you're making students come out even less educated because the students who actually need help in school now get even less attention with more people who now take up this attention. Also, the students who can actually learn on their own now have to deal with a more problematic classroom. More people + less attention for each = more time needed to catch everyone up. As well, I really, really wish that classrooms don't become mini-hallways when it comes to getting around. I guess there is a benefit to this: people who want to study on their own can now use their cellphones to study with a smaller chance of getting caught because of the decreased attention from the teacher for all the students. Wait...what? They're banning cellphones too?
<h2>The Cellphone Ban</h2>
<p>Yet another beautiful example that proves my point. The cellphone ban targets students who use their cellphones to play games during class. These are the people that are obviously not committed to learning and could really care less. School simply wants to educate them so that they become more than just Robux trees. However, this cellphone ban also targets the minority (who will be more educated in the end) as well: those who use their cell phones to study. I use my cellphone in class to study my Anki decks. I cannot stand being unproductive, so I whip out my cell phone and trudge through my Anki flashcards whenever we're learning a subject I already know or when we're not doing anything currently directed at me (e.g. checking homework, a work period with my work finished, etc.) However, this cell phone ban will mean that whenever a teacher spots a cellphone without prior consent, alarms go off and security busts in to snatch my phone away and scold me on how I should be paying attention to...nothing, as there's no benefit in paying attention to a topic not directed to you in any way, shape or form. Of course, I could get prior consent from teachers before using my phone but this requires me to either interrupt a lesson (when the teacher is teaching something I already knew) or to bother the teacher when they're working during a work period. Of course, if you gave people the option of not needing to pay attention if they had other productive work to do, practically everybody would overestimate their knowledge, myself included...</p>
<h2>The Ridiculousness of Tests</h2>
<p>School checks your knowledge by giving you tests. This is the process:
<ol>
<li>Bombard poor students with facts about a subject and scold those who don't pay attention even when they already understand the topic well (I'll come back to this later)</li>
<li>Tell these students that a test is being given out and those who fail it will have their low mark follow them around until the end of time. You also threaten to give a zero to those who refuse to take the test.</li>
<li>Test Day - The whole class is absolutely stressed out because they're worried that they'll get a terrible mark that'll haunt them for the rest of their lives. Why? Because they either didn't get the topic enough, didn't have enough time to get help or didn't receive as much attention as they should've.</li>
<li>Post-Test Day - A lot of the students become depressed because they find out that their answers didn't match up with others and then end up in an unproductive rut with only the depressing thought of a terrible mark in their head.</li>
<li>You find out that half the students failed the test but because you have no time to review the topic and must proceed with the curriculum you don't plan to do a makeup test.</li>
</ol>
<p>In the end, what have you done? You've pointed out the flaws in the students' knowledge and then proceeded to do nothing about it. Why? "Because you have no time." That's a ridiculous excuse. You should've prepared the students more by giving the people who need the attention and help more attention and help. Take a look at this idea:</p>
<ol>
<li>Before actually teaching the subject, you give a harder-than-normal test about the subject that still incorporates the topics needed to learn but omits questions where students can get correct if they're lucky (i.e. no multiple choice)</li>
<li>Pre-Test day: The students aren't stressed because they know that this mark won't haunt them. Rather, it's a test that shows you what you don't know without penalizing you for it.</li>
<li>Post-Test day: The students go home stress-free and the teacher discovers that some students know the topic very-well while some only know a few topics well.</li>
<li>The teacher uses this information to design a schedule that will only involve the students that need help (based on the test) or the students who think they need help (based on asking). This way, there are fewer students who are learning at the same time and more attention is brought to them while the other students don't waste time and can maybe focus on learning the topics they don't understand early or can help one another silently with the topic. Or, if they aced everything, they should be allowed to study on their own. I agree not to let students play games because this would only distract the other students' focus and wouldn't benefit that student in any way. As well, the teachers can allow the students who did well to help the students who did poorly, which increases efficiency as well in active learning because the students who know it well can actively recall and the students who need help can actively learn by asking questions and listening to improvements. Compare this to the very passive style of doing homework and taking it up, an approach of having directed and personal attention can benefit a student much more than just passively listening and passively doing.</li>
<li>Now that the students who needed help and attention received the most help and attention they can get, they should feel a lot more confident. As well, the teacher should now have extra time left to help because they didn't need to explain as much and the students who needed help had already got help from their peers. The teacher can use this review time to take up any questions or review material the students seem unfamiliar with. They could even give the pre-test out again to see if the students now understand the questions and then filter out the students who are still struggling and direct a ton of attention on them after the results.</li>
<li>Test time: Everybody is less nervous because they are confident that they know the material. The students who aced the pre-test should have little to no difficulty writing the final test, and the students who struggled should now be a lot more confident because they had learned the topic once again and perhaps have even done a re-pre-test and aced that as well. The only mistakes you should expect are silly mistakes from not reading the question properly or misunderstanding what the question asked for.</li>
<li>You end up with educated students who have actually learned the material instead of just memorizing useless facts and forgetting them right after the test. You also end up with students who have used the free time during the review of subjects already familiar to them to educate themselves even further.</li>
</ol>
<p>Disclaimer: I'm not a teacher or an education staff so I have no idea if this idea would work or not. I also have no idea if the budget would support this learning style or not (however I assume that it should be worth it because the students are more educated in the end). I'm also aware that there are some subjects where no students actually know the subject well enough and all the students require help, but the pre-test would still be valuable in increasing efficiency in the case that there is a student who knows the topics and the teacher can use them to help explain and create a more active learning environment for them.</p>

<h1>What Can School Do Better?</h1>
<p>Besides implementing some similar ideas to the ones I've provided, there are many ways that school can be improved in terms of having a more free choice of education. One idea is making the course curriculums more accessible and making aware consequences of choosing particular courses. I got trapped in my selection for computer science which ended up being a repeat of everything I've learned before and then realizing that this makes summer school mandatory if I wish to have a free choice of a course for the following year. I don't recall them ever really warning about this and they never provided access to what the difficulty of the course I selected was going to be, and this means that I wasted a whole semester as well as a whole month in the summer (which I will refuse to simply 'take' and will follow up with strict guidelines for myself - more about that when the course approaches). This would allow students to contemplate their choices, especially when wrong choices result in the waste of a student's time during time they deserve to have free.</p>
<p>Another improvement I would suggest for school is implementing a grading system based more on improvement than incompetence. When we receive low scores, we don't really learn from them because we don't understand exactly where we went wrong. We only receive a number representing the combination of our faults without really specifying in which areas of the subject our faults lie. This hinders us from really realizing what we need to improve. Instead, basing a grading system on detailing specific steps and resources we can use to improve instead of summing everything up with a number can theoretically obtain better results than just pointing out what was wrong.</p>
<p>Homework is another controversial (at least, among the students) aspect of schools. Why? Because they steal time that really should be left for how the students want to use that time. Homework exists because the time available in school isn't sufficient to provide examples and simulate real applications of knowledge. I don't argue with homework that genuinely helps students, I argue with repetitive homework that doesn't really help the students if they already understand the topic. If a student shows understanding of a subject, they should be allowed to not finish homework they don't think will benefit them. You shouldn't punish these students for not doing redundant questions, because it only becomes a waste of time and energy for them in the end. However, I completely agree that a student should not be able to freely decide to not do homework based on their own belief of their own knowledge. This is exactly why I think the pre-test system would be a major improvement to our school system because it would really save time for both the students and teachers.</p>
<p>Of course, there are many other improvements, both big and small, that would benefit the system more overall. It's interesting to see that if you start to shift your attention for making school more 'time-friendly' for those who don't need it as much, you start providing the students who do need school more access to really learning what school is trying to teach. In other words, by solving the problems for a minority (the people for which school is a waste of time), we start making a more positive impact on the majority (the students who need school for learning material that can be useful to their daily lives).</p>

<h1>Conclusion</h1>
<p>Look, I'm not here to annoy teachers. I don't want to give them a hard time. I respect what they do, but I just don't respect how they are made to do it, which is not their fault. I'm also not very interested in demolishing every school or waging war on these institutions. I'm just advocating that one should use schools for the pure purpose it's intended for: for learning. Yes, you're at school to learn. So...learn. This is the reason why I gave up learning computer science at school because of how slow the curriculum is. Instead, I chose a subject that I'm genuinely interested in. How about the mandatory subjects that I take? I push myself to learn more than they give in ways that they can't teach. For example, I learn more vocabulary in French. I learn on my own in math by bringing my own textbooks to study from while class goes on. I take out my phone and study when I have free time (e.g. when I'm done my work early). I don't support wasting time at all, and that's why I don't support schools, nor the people who don't want to go to school because of reasons that contradict its purpose. Look, I'm here to help people who want to be smart who are hindered by schools, not those who don't care about getting help and only don't want school so they have more time to waste. I'm not here to change a stubborn mindset; that's not my job. If you don't want to learn, then I'm fine with that. I'm not okay if you stand by my side with my opinion about schools, choosing to complain by my side while believing they shouldn't be mandatory because you don't care about learning. Rather, I'm striving to help those stuck from learning further, by inspiring people to get more motivated in doing what school limits them from doing. That's really what my website is about...isn't it?</p>
<p><em>"School is for educating people, not for making them smart. If you want to be smart, you can't rely on school for holding your hand. It's up to you to hold your own."</em></p>
