<h1>Impulsiveness</h1>
<p>I&rsquo;ve recently been reading &ldquo;The Motivation Hacker&rdquo; by Nick Winter. In his book, he talks about impulsiveness, an idea stemming from the Motivation Equation. This equation shows that high impulsiveness results in low motivation. Nick Winter proceeded to say that it takes a large amount of effort to focus around distractions. Therefore, by removing these distractions, one doesn&rsquo;t need this extra effort in retaining their motivation in continuing with their current task.</p>
<p>However, as you and I both know, removing distractions isn&rsquo;t as easy as snapping a finger. Distractions exist in many fashions and some are much harder to avoid than others. This article will provide different ways of dealing with these distractions in the form of &ldquo;restrictions.&rdquo;</p>

<p>But first, it&rsquo;s crucial to reveal a greater problem...</p>

<h1>Staying Out of Justification</h1>
<p>Distractions don&rsquo;t just distract one from their current task, but can also hinder one&rsquo;s judgment in starting and ending a task. We must be able to distinguish the real distractions in our lives and avoid justifying them as needed or beneficial.</p>
<h2>Justifying Entertainment</h2>
<p>One large distraction that we must overcome is our justification to seek entertainment in a day of productivity. How? In our day and age, these types of distractions hide behind the mask of &lsquo;entertainment&rsquo;. Our society encourages the wrong mindset of &lsquo;breaks are for enjoying oneself.&rsquo; Thinking in these terms deals great damage to one&rsquo;s productivity and efficiency. Media and entertainment associate entertainment with &lsquo;acceptable breaks&rsquo; from life while simultaneously making their products as addicting as possible. This leads to procrastination from extended and unfulfilling &lsquo;breaks&rsquo; which lead your motivation to a pitfall trap.</p>
<p>The key? Don&rsquo;t value entertainment in a break. Yes, a break is for relaxing. However, multitudes of more efficient (and effective) ways of relaxing exist, ones that don&rsquo;t require entertainment. I&rsquo;m not against breaks, for I have had multiple experiences where a break would render me more productive in the long run and give me the chance to clear my mind. When I (wrongly) justify breaks as entertainment, these breaks become prolonged and leave me feeling lazy and demotivated.</p>
<p><strong>Don&rsquo;t submit to cheap entertainment for clearing your mind.</strong></p>

<h2>Justifying Incorrect Prioritization</h2>
<p>Another distraction lies in the form of productivity. While it may be &lsquo;productive&rsquo; to continue working on a task, biased prioritization and poor time management can damage the structure of your day. Don&rsquo;t justify putting something important off for the sake of wanting to work on another less important task. However better it may be than pure unproductivity, it&rsquo;s still unbeneficial to justify flawed time management.</p>
<p>Perhaps a common example of such justification lies in homework. Admittedly, some types of homework are more pleasant or manageable than others. However, justifying finishing one before the other based on this scale of ease will lead you to time deficiencies. Rather, using the deadline to prioritize would act as a better method would (assuming you have enough time overall to complete everything). One form of procrastination is the justification of being able to finish the more demanding tasks when they&rsquo;re the most demanded.</p>

<h1>Entertainment</h1>
<p>Entertainment is probably the most common source of impulsiveness. We all would rather pursue a more entertaining path if both ways produced the same reward. However, it&rsquo;s often the case that when we choose the path of entertainment, we sacrifice a large deal of efficiency in doing so. Oftentimes, these losses in efficiency are so detrimental that turning towards restrictions would start becoming a novel idea.</p>
<p><em>You may notice my blunt attitude towards the topic of entertainment. To confirm, I&rsquo;m only strongly against entertainment used an escape route from one&rsquo;s current task. Besides my personal negative experience, many people and the media promote this mindset that &lsquo;there&rsquo;s nothing wrong with this use of entertainment&rsquo; when they have ulterior motives for telling such a lie. You should not take lightly a misunderstood topic that damages a mindset of success.</em></p>
<p>I would be pretty hypocritical if I said that I marked entertainment as &lsquo;utterly useless.&rsquo; I can picture many scenarios where entertainment can bring motivation to the table. However, I am starting to see through the lies that society tries to impose. &ldquo;Everybody needs some entertainment to clear out their mind&rdquo;, &ldquo;entertainment is the best way to clear out your mind&rdquo;, &ldquo;entertainment will make you less stressed.&rdquo; No, rather, entertainment branded as an escape rope is one of the most toxic mindsets you can have. I&rsquo;m against entertainment marketed as the &lsquo;must-have&rsquo; factor in relieving oneself.</p>
<p>Entertainment manifests from the viewpoint of perpetual amusement. Society values short-term rewards over long-term ones and hyperbolically discounts the rewards we retain in the future when we look at the bigger picture. Don&rsquo;t let society fool you when they portray your addiction to entertainment as &lsquo;helpless&rsquo;. Rather, get yourself up and throw away everything society&rsquo;s ever told you about having fun. Value the bigger picture.</p>

<h2>When Entertainment is Acceptable</h2>
<p>I&rsquo;ve mentioned that certain scenarios where entertainment is okay do exist. Specifically, these situations allow entertainment to bring a positive ratio of extra effort to motivation. Take Habitica, for example. Habitica uses game mechanics (a source of entertainment) to motivate one to complete their tasks. Of course, the gamifications sometimes do distract from the main purpose of completing the tasks you haven&rsquo;t completed. However, the &lsquo;extra distractions&rsquo; to extra motivation tradeoff is much valued for me. I&rsquo;ve tried many other To-Do apps, but for me, Habitica was the best one in giving me the motivation to get things done.</p>
<p>When you have fun doing something productive, is that a sign of inefficiency? Of course not! That&rsquo;s a sign of excess motivation, a good thing to have. Again, you should avoid entertainment when it seeks to keep you from facing something worth a greater purpose. If you have fun doing a task that you would have to do regardless, you use that entertainment for a good cause. However, if you&rsquo;re tackling a low-priority task because it gives you entertainment, you should aim to fix this motivation deficiency that&rsquo;s affecting your time management skills. You should always prioritize the value of a task over the enjoyment you receive.</p>

<h1>Restrictions</h1>
<p>I&rsquo;ve explained the dangers of falling into society&rsquo;s cushioning words. You must now fight against them and commit to restricting yourself from entertainment used as an escape route.</p>
<p>The main purpose of a restriction is to lower impulsiveness which in turn raises motivation. Restrictions seek to prevent you from wanting to tackle (or think about) something else besides your current task. Common examples include wanting to play video games, spend time with friends, or having too many things on your that negatively affect your concentration.</p>
<p>Unfortunately, justification is a large part of a human&rsquo;s nature. It is challenging to catch yourself justifying something wrong into something acceptable, much less stopping yourself from following through with the justification. Restrictions save yourself from this extra effort. By restricting yourself, you find no purpose in justifying bad behaviour because you can&rsquo;t follow through with this behaviour anyways. I experienced this scenario when I temporarily disabled my website blocking program, Cold Turkey, during an exceptional event. After I finished what needed accomplishing with Cold Turkey disabled, I forgot to re-enable the blocks. Afterward, I found that I didn&rsquo;t try to re-access the distracting websites while having stared at the block screen weeks before the event. Because I&rsquo;ve learned to live with the simple truth, that I can&rsquo;t access distracting websites, I stopped trying and stopped justifying these attempts. This allowed me to accomplish more work than I would&rsquo;ve if I kept thinking about the thought of submitting to these distractions.</p>

<h2>Inability-Motivated Restrictions</h2>
<p>After failing to plan for my day and succumbing to the YouTube pitfall, I found myself in an unmotivated rut. As I checked my phone, I noticed the 1,000+ count of Anki cards that I had to study. Being myself, I knew that if I stayed near my computer, I would not get anything done. I decided to commit to the impulsive decision to leave my computer and only bring my phone to the park. There, I would be unable to do pretty much anything besides studying Anki on my phone. At the park, I whittled through my flashcards while walking around for 2 hours. It wasn&rsquo;t fun, but I finished studying 600+ Anki cards, compared to the zero if I had decided to avoid this restriction.</p>
<p>One of the restrictions at play in this scenario is the physical restriction of being incapable to submit to impulsiveness. In other words, we are physically restricted from doing anything impulsive and therefore our brain stops thinking about it. This allows us to muster this otherwise wasted focus on the task at hand.</p>
<p>Perhaps the more popular approach with this type of restriction is through website blockers. By putting yourself in a position where you are physically incapable of accessing distraction websites, you allow yourself to focus well on the task at hand. Another similar inability-based tool is a writing app that doesn&rsquo;t allow you to look at what you&rsquo;ve written. This way, you can focus on writing the words instead of the peripherals of grammar or formatting.</p>
<p>Unfortunately, it is often hard to physically remove ourselves from distractions in a way that doesn&rsquo;t affect our original goal. For example, a task might require a computer, a gateway to a distraction-filled world. Of course, website blockers and other tools do exist, but you&rsquo;ll find that it is very hard to block everything that distracts you.</p>

<h2>Consequence-Motivated Restrictions</h2>
<p>Nuclear restrictions (inability-motivated restrictions) aren&rsquo;t always necessary, and oftentimes it&rsquo;s very hard to assert a definite restriction impossible to get past. You can motivate yourself to follow non-nuclear restrictions by using consequences. This is why you may have noticed my $5 bet with my friends to stay out of the inn in Habitica. A nuclear restriction is next to impossible in such a situation. We use the inn itself to escape another powerful consequence: dealing damage to friends during a boss battle (perhaps guilt-motivated restrictions better fits this scenario). Another popular example of a consequence-motivated restriction would be Beeminder, an app that charges you money if you fail to get your tasks done. I assume that we all value money enough to create motivation in ourselves. However, with consequence often comes weaseling, even at the sake of moral choices.</p>
<h3>Reward-Motivated Restrictions?</h3>
<p>Restrictions restrict you from doing something. At first, rewards don&rsquo;t seem to fit this category. However, one could classify them as consequence-based by claiming &ldquo;the consequence is not getting the reward.&rdquo; I believe rewards are better suited towards the other factors in the motivation equation (e.g. Expectancy & Value). As follows, I won&rsquo;t go into as much detail in this article.</p>
<p>Habitica also rewards you for completing tasks. Some examples include getting gold, finding equipment to dress your character and many other gamified features that we would consider as rewards. Personally, I often don&rsquo;t find these rewards motivating enough and don&rsquo;t feel too restricted to achieving them. Habitica does have more powerful restrictors using consequence and guilt. I talk about these in their appropriate sections.</p>

<h2>Guilt-Motivated Restrictions</h2>
<p>One of the large reasons I stopped using Beeminder was because I found myself weaseling out of the punishments. I would often find myself lying and justify my failure to avoid guilt. However, if you&rsquo;ve noticed my MonthlyChallenge after creating the $50 bet with my friend, you&rsquo;ll notice that I never deliberately missed a day after that. In other words, knowing that I really can&rsquo;t lie to my friend (or I would feel extremely guilty!) motivated me to get these tasks finished (which only take 10 minutes or so). Guilt-Motivated Restrictions can play a huge advantage in giving motivation, especially combined with other motivating factors (including other restrictions themselves).</p>
<p>You may have seen my SSS workspace/setup. I&rsquo;ve set up this workstation apart from where I normally reside. My SSS setup is in a room dedicated to intense focus sessions where I concentrate on getting one thing done. It gives off the unique atmosphere feeling of having created a separate space for a reason. I feel obliged to follow the reason because of the guilt otherwise, which would be an example of a guilt-motivated restriction. I would feel guilty using a place improperly that I spent all the effort furnishing for proper use. If I simply regarded it as another room, I would feel guilty wasting my effort and the effort of others for preparing a purposeless extension of my room.</p>

<h2>Atmosphere-Motivated Restrictions</h2>
<p>It is very possible that a location garnishes a reputation for being distracting. There&rsquo;s a large difference between studying in a room where you often play video games and studying in a library. Both give off a subtle atmosphere that can either hinder or ameliorate your focus and concentration on what we need to finish. By putting yourself in a restricting atmosphere, even to your discomfort, you allow your brain to realize that there&rsquo;s no getting out of your task and your impulsiveness starts to lower.</p>
<p>An example of this restriction technique used in my life is with my super study sessions. Along with providing a guilt factor, the simple atmosphere of a simple layout and an obvious purpose allows me to focus on my work as distraction-free as possible. Of course, you may not have an extra room lying around as I do. The other option is simply rebranding an existing atmosphere&rsquo;s reputation if you wish to retain that physical location. Cleaning one&rsquo;s room could end up giving off a much more pleasant and clear atmosphere than a room that&rsquo;s very hard to navigate.</p>
<p>There&rsquo;s another prevalent method of this type of restriction. We don&rsquo;t always characterize an atmosphere by its location. One can also classify an atmosphere based on their use of it, often with others. &ldquo;Study With Me&rdquo; videos are a popular manifestation of this restriction. When you are around other motivated people in studying, you&rsquo;re much more likely to have a better concentration in your task at hand. Take the simple scenario of trying to study while your friend is playing video games beside you. Their video game will distract you and you might even fall to joining them in their pursuit for nothing. Restrict yourself from these distractions by putting yourself in a &lsquo;working&rsquo; atmosphere and you&rsquo;ll find that your concentration exponentially increases.</p>

<h1>Conclusion</h1>
<p>After finishing this article, I started to realize that restrictions are a part of a broader category: motivators. However, we mainly use restrictions to decrease impulsiveness, while motivators are general ideas of increasing one&rsquo;s motivation (either by increasing expectancy, reducing delay, or increasing value). I&rsquo;ll go more in-depth on these other topics in the future. I think restrictions was a nice topic to start with because it is potentially the biggest demotivator in our lives. If we can learn to restrict ourselves and value the bigger picture, we can go a long way in reaching our goals.</p>
<em>The first step is the step that starts it all.</em>
