<p>It's over...except it's not.</p>
<h3>The Process</h3>
<p>The WES19.5.8 was a challenge I took upon during the Victoria Day long weekend. I aimed for 30 hours of work within 72 hours whittled to around 45 hours of free time.</p>
<p>The first day was the most successful (in terms of hours). I slept at 6:30 PM on Friday and woke up at 12:00 AM on Saturday. I worked until 5:30 AM when sleep got the better of me and I ended up choosing to take a 1-hour nap. On Saturday, I was faced with a pretty big exception. I decided to allow myself to allocate time for this exception, except that the initial time estimated was pretty far off from the actual time. This exception took from 2:30 PM to around 10:00 PM and forced me to change my sleep schedule. I ended up waking up at 5:30 AM the next day. Sunday was also a source of exceptions that I underestimated, but not as extreme as Saturday's. Monday was the real day that I had to get stuff done, for there were minimal exceptions that I had to deal with. I finished the WES19.5.18 at around 9:30 PM on Monday and had to finish my homework that was due on Tuesday after that...</p>
<h3>The Aftermath</h3>
<p>The brilliant idea of creating flashcards from my textbooks came to me on the third day. Good ideas always come at the most inconvenient times...</p>
<p>The first two days of my WES were my attempting to pursue a more active style of learning with taking notes only to become too lazy to take notes and end up just zombie-skimming the textbook and dozing off every once in a while. It was only on the third day (well, actually the idea came when I was trying to fall asleep on the end of the second) to create flashcards for the $40 app I had bought on the App Store a while ago: Anki. I use this app for memorizing french vocabulary and related it to what I was doing now: trying to retain facts so that I could learn them with a more active approach. I would often find that I hesitated to include information that wasn't directly what I wanted to learn, such as wanting to know the actual syntax and code rather than what the code really meant. I learned this the hard way when I tried testing myself on what I learned and failed to recall even the basics. After using Anki and returning back to that chapter I had struggled with, I managed to breeze through the test I created for myself without needing to rely heavily on the textbook for the exact code and instructions. This truly taught me how learning well is better than learning quickly. I hope to retain this philosophy for my SBS where it's crucial to value learning well as I take on the complicated subject I wish to learn.</p>
<h3>Streaming</h3>
<p>A twist that I chose to take with this SSS is by live streaming the event. I was focused more on just keeping myself accountable rather than making the stream enjoyable, which now looking back, could've been something that I would improve on. One step forward is to record my screen live so that viewers can see exactly what I'm doing when I'm working on my screen (which I did, a lot). As well, I'm still debating a method of recording my voice with something like the "push to talk" feature so that I can make some comments about things to make the stream more interesting. I definitely put minimal effort and used live streaming as a last-minute idea, so I think there's a lot of room for improvement if I wish to try this idea again.</p>
<p>Having thought about this, increasing the quality of my live stream increases the chances of somebody showing up and staying which in turn increases its very purpose in the first place: accountability. Of course, everything comes with a negative side. The negative side I came across while live streaming is that I found myself often distracted with my constant checking of the stats and video. However, given the success, I would say this trade off could be considered worth it.</p>
<h3>Struggles</h3>
<h4>"The Research Rabbit Hole"</h4>
<p>I struggled with many things with the WES19.5.18. One of these was the research rabbit hole. I would often find myself interested in a topic that I had read about and wanted to quench my thirst and my curiosity for more knowledge. This often led to me searching up the answers to these questions of mine and ultimately leading me to another interesting topic and having me succumb to the rabbit hole of falling ever further from my initial topic of focus. A solution to this problem that I had once learned was keeping a notebook near me and writing down further research topics when they came to my head instead of finding them right away and distracting me. This way, I wouldn't need to think about it and get distracted by a side topic that is ultimately not too relevant to the topic I'm studying.
<h4>Staying Awake</h4>
Another struggle that I had to face was trying to stay awake. Interestingly, this problem only arose when I was passively learning and just reading the textbook without really practicing recall. In this event, my mind doesn't really have a handle for gripping on which leads to a diffused focus and a craving for sleep. When I was actively making flashcards and trying to repeat the topic in my own words when putting it into the flash cards, my mind had a grip on this activeness and it always had something to do with the information it was collecting. This tactic removed the problem of new information weighing it down for it provided a way to use that information to keep it running and awake.</p>
<h4>Lack of Preparedness</h4>
<p>This is perhaps the most ridiculous reason for passive learning that I've ever encountered with any SSS I've done. After waking up at 12 AM on Saturday to get started with work, I find out that I forget to bring extra lead for my lead pencil. "Oh. No worries. I'm pretty certain that there's enough lead for 8 hours or so." Maybe that was an overestimate if I had maybe one stick of lead, but I ended up finding out that I only had a 2cm piece that was about to become useless when used a bit more. Of course, I was a victim of another one of the laws of life: "You only have something when you don't need it, and you only lack something when you do." Of course, the natural solution was to type out my notes as I really didn't want to ring the doorbell at 12 AM because I needed a pencil. Typing my notes, however, quickly revealed a problem...it turned my focus over to the syntax rather than the meaning of my content. This meant that I wasn't understanding <em>what my writing meant</em> as much as <em>what my writing was.</em> This brings across an interesting conundrum: when you're slow at typing you lose focus on the meaning because your focus is concentrated on finding the location of your desired letter rather than what lies beyond the letters of your text. When you're fast at typing, you start losing focus on the meaning because you end up typing way too much that really conserve more of the syntax than the meaning of the context...</p>
<h4>It's not over</h4>
<p>"Never stop learning." So...why do we? The truth is, learning is a process that isn't as simple as reading a textbook and imprinting the information into your brain. Rather, learning is like one of those farm games we all have tried before. A subject is represented as a plot of land we need for growing crops. At first, we can only grow small things that don't take that much time on this plot and we must constantly remember to check back in order to harvest our knowledge. However, we eventually "level up" the plot enough so that we can plant more complicated crops that don't need as much attention as when we first started, but will still die if we don't take care of them eventually. If we don't plant crops in the plot, the soil will dry and the plot of land will degrade.</p>
<p>There is no infinite crop. Likewise, there is no such thing as mastering a subject to the point where you can't improve any further. When we learn a new subject, we buy a new plot of land that must be taken care of as we continue to learn more about that topic. We must continue to look after the previous plots before this purchase while now putting effort into maintaining this new crop of land. However, it's objectively better because we can now develop our farm even more and harvest more crops than if we were to only buy one plot of land. Likewise, it's not enough to just develop one specific subject and shying away from others because of the fear of needing too much work, but rather it's best to try and develop a range of subjects/plots to grow upon.</p>
<p>How does this relate to my WES? Well, I learned the hard way that reading a textbook and thinking that I wouldn't have to return to it isn't enough. I can't treat a textbook like a checklist. Rather, I learned much more when I put these concepts into Anki cards and still practiced them after the WES was over. I still had to take care and use my plot of land and harvest the reward of knowledge using effort as my water. The mindset of a "checklist textbook" is harmful and can seriously end up as a waste of time. I need to treat my learning process like a farm game where I need to continue to care and play if I don't want to forget and ruin my farm of knowledge (which speaking of it, somebody should totally make a game like that).</p>
<h4>Lessons</h4>
<p>I'm really glad that I was able to succeed with this SSS unlike the others I've attempted. I think setting up a separate room and leaving my regular workstation was a big factor in the success of this SSS. By using pre-commitment, I become more likely to follow through and less likely to give up because of all the setup and preparation that would be wasted if I were to quit. I think the biggest lesson I've learned is that simply telling yourself that you're going to do an SSS does not certify that you will learn a lot from it. I think that you must make a conscious effort to actively learn and to actively engage in remembering what you've learned in order to be successful. The beauty of learning doesn't arise from the pace but from the content. As such, an SSS should be treated as a session that allocates a lot of time that you can use to master this content rather than trying to breeze through everything that you need to complete. This WES is a step further to being successful when it comes to the SBS and further sessions down the road. I hope that my experience has potentially encouraged you to stride further in your studies and to put more deliberate effort in becoming a more knowledgeable person than you were the day before!</p>
